# Docker compose file managed by Spring Boot for
# setting up needed containers during development.
services:
  db:
    image: mariadb:11.2
    container_name: maria_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge