/*
 * Copyright 2026 Sweden Connect
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package se.swedenconnect.oidf.registry.registrations.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import se.swedenconnect.oidf.registry.registrations.model.RegistrationStatus;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Represents a registration request visible to an operator.
 *
 * @author Per Fredrik Plars
 */
@Data
@Schema(name = "Registration")
public class RegistrationDto {

  @Schema(description = "Registration ID", accessMode = Schema.AccessMode.READ_ONLY)
  @JsonProperty(access = JsonProperty.Access.READ_ONLY)
  private UUID id;

  @Schema(description = "Intermediate (TaIm) this registration belongs to")
  private UUID taimId;

  @Schema(description = "Registration flow used for this request")
  private UUID registrationFlowId;

  @Schema(description = "Entity identifier of the applicant", example = "https://example.com/entity")
  private String entityId;

  @Schema(description = "JWKS snapshot from entity configuration at time of registration")
  private String jwks;

  @Schema(description = "Entity configuration metadata snapshot")
  private String metadata;

  @Schema(description = "Proposed metadata_policy generated by PolicyCreationStep")
  private String metadataPolicy;

  @Schema(description = "Trustmarks requested in the application")
  private String trustmarksRequested;

  @Schema(description = "Current status of the registration request")
  private RegistrationStatus status;

  @Schema(description = "When the request was reviewed by an operator", accessMode = Schema.AccessMode.READ_ONLY)
  @JsonProperty(access = JsonProperty.Access.READ_ONLY)
  private LocalDateTime reviewedAt;

  @Schema(description = "Identity of the operator who reviewed the request", accessMode = Schema.AccessMode.READ_ONLY)
  @JsonProperty(access = JsonProperty.Access.READ_ONLY)
  private String reviewedBy;

  @Schema(description = "Reason provided by the operator when rejecting the request")
  private String rejectionReason;

  @Schema(description = "When this registration was created", accessMode = Schema.AccessMode.READ_ONLY)
  @JsonProperty(access = JsonProperty.Access.READ_ONLY)
  private LocalDateTime createdDate;
}