ALTER TABLE entities
    ADD COLUMN created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN last_modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN created_by VARCHAR(255),
    ADD COLUMN last_modified_by VARCHAR(255);

ALTER TABLE trustmark_subject
    ADD COLUMN created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN last_modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN created_by VARCHAR(255),
    ADD COLUMN last_modified_by VARCHAR(255);

ALTER TABLE policies
    ADD COLUMN created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN last_modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN created_by VARCHAR(255),
    ADD COLUMN last_modified_by VARCHAR(255);