server:
  port: 8010
  compression:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'


spring:
  application:
    name: EntityRegistryService

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:mariadb://db:3306/testdb
    username: test
    password: test

  flyway:
    enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  docker:
    compose:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: file:config/local/public_auth_cert.pem
          audiences: https://registry.local.swedenconnect.se

logging:
  level:
    se:
      swedenconnect:
        oidf: debug



credential:
  bundles:
    keystore:
      signkey:
        location: file:config/local/rsa1.jks
        password: Test1234
        type: JKS
    jks:
      federationapi:
        store-reference: signkey
        name: "FederationAPI-JWKSignkey"
        key:
          alias: rsa1
          key-password: Test1234

openid:
  federation:
    registry:
      federation_service_api:
        issuer: "http://oidf-registry.swedenconnect.se"
        sign-key-alias: federationapi
      instances:
        - instance_id: "123e4567-e89b-12d3-a456-426614174000"
          name: "Swedenconnect"
        - instance_id: "223e4567-e89b-12d3-a456-426614174001"
          name: "ENA"
