package se.swedenconnect.oidf.entity.registry.audit;

public enum RegistryAuditEvent {

  ENTITY_CREATED,
  ENTITY_UPDATED,
  ENTITY_DELETED,
  ENTITY_READ,

  POLICY_CREATED,
  POLICY_UPDATED,
  POLICY_DELETED,
  POLICY_READ,

  TRUSTMARK_SUBJECT_CREATED,
  TRUSTMARK_SUBJECT_UPDATED,
  TRUSTMARK_SUBJECT_DELETED,
  TRUSTMARK_SUBJECT_READ,

  FEDERATION_API_ENTITY_READ,
  FEDERATION_API_POLICY_READ,
  FEDERATION_API_TRUSTMARK_SUBJECT_READ
}
