/*
 * Copyright 2026 Sweden Connect
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package se.swedenconnect.oidf.registry.organization.model;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import se.swedenconnect.oidf.registry.infrastructure.persistence.BaseEntity;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * A domain claimed by an {@link Organization}, mapped to the {@code organization_domain} table.
 *
 * <p>The owning {@link Instance} is carried on the row itself, denormalized from the organization, so that the
 * database can enforce the tenant-wide rule that only one organization holds a given domain at a time. The
 * {@code held_domain} generated column and its {@code uk_instance_held_domain} unique key implement that rule:
 * the column repeats {@code domain} while the claim is {@link DomainStatus#PENDING} or
 * {@link DomainStatus#VALIDATED} and is {@code NULL} once it is {@link DomainStatus#REJECTED}, and NULLs do not
 * collide. It is generated by the database and therefore deliberately not mapped here.
 *
 * <p>The {@code domain} value is a bare, lower-cased hostname — no scheme, no path, no port and no wildcard.
 * Registration requests are only accepted when the host of the requested entity identifier equals, or is a
 * subdomain of, one of the organization's {@link DomainStatus#PENDING} or {@link DomainStatus#VALIDATED}
 * domains.
 *
 * @author Felix Hellman
 */
@Getter
@Setter
@Entity
@Table(name = "organization_domain",
    uniqueConstraints = @UniqueConstraint(name = "uk_organization_domain",
        columnNames = {"organization_id", "domain"}))
public class OrganizationDomain extends BaseEntity {

  @Id
  @Column(name = "domain_id", columnDefinition = "char(36)", nullable = false, updatable = false)
  @JdbcTypeCode(SqlTypes.CHAR)
  private UUID domainId;

  @ManyToOne(fetch = FetchType.LAZY, optional = false, cascade = CascadeType.DETACH)
  @JoinColumn(name = "organization_id", nullable = false)
  private Organization organization;

  @ManyToOne(fetch = FetchType.LAZY, optional = false, cascade = CascadeType.DETACH)
  @JoinColumn(name = "instance_id", nullable = false)
  private Instance instance;

  @Size(max = 255)
  @Column(name = "domain", length = 255, nullable = false)
  private String domain;

  @Enumerated(EnumType.STRING)
  @Column(name = "status", length = 20, nullable = false)
  private DomainStatus status;

  @Column(name = "rejection_reason", columnDefinition = "TEXT")
  private String rejectionReason;

  @Column(name = "reviewed_at")
  private LocalDateTime reviewedAt;

  @Size(max = 255)
  @Column(name = "reviewed_by", length = 255)
  private String reviewedBy;
}
