/*
 * Copyright 2026 Sweden Connect
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package se.swedenconnect.oidf.registry.controller;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.resttestclient.autoconfigure.AutoConfigureRestTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.web.client.RestClientResponseException;
import org.testcontainers.containers.MariaDBContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import se.swedenconnect.oidf.registry.ApiClient;
import se.swedenconnect.oidf.registry.api.EntitiesApi;
import se.swedenconnect.oidf.registry.api.model.FederationEntity;
import se.swedenconnect.oidf.registry.api.model.FederationEntityWithModules;
import se.swedenconnect.oidf.registry.fixture.JwtTestUtils;
import se.swedenconnect.oidf.registry.guioperations.JwksKeysCacheService;
import se.swedenconnect.oidf.registry.guioperations.dto.JwksPayloadDto;
import se.swedenconnect.oidf.registry.infrastructure.auth.domain.OrganizationRecord;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

/**
 * Integration tests for Entity CRUD operations (Federation, Hosted, Subordinate) using the generated OpenAPI client.
 *
 * @author Per Fredrik Plars
 */
@Slf4j
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Testcontainers
@AutoConfigureRestTestClient

class EntityCRUDIT {

  private static final String TENANT = "Swedenconnect";

  /**
   * A second tenant, configured with function_groups: ena, swedenconnect — it shares "swedenconnect" with
   * {@link #TENANT}.
   */
  private static final String SHARED_FUNCTION_GROUP_TENANT = "ENA";

  @Container
  @ServiceConnection
  public static MariaDBContainer<?> database = new MariaDBContainer<>("mariadb:11.2");

  @LocalServerPort
  private int port;

  @Autowired
  private JwtTestUtils jwtTestUtils;

  @MockitoBean
  private JwksKeysCacheService jwksKeysCacheService;

  private EntitiesApi entitiesApi;


  @BeforeEach
  void setUp() {
    final ApiClient apiClient = new ApiClient();
    apiClient.setBasePath("http://localhost:" + this.port);

    // Configure authentication
    apiClient.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.PM));

    entitiesApi = new EntitiesApi(apiClient);

    // By default payload has empty names → empty signingKeyId list passes validation
    when(jwksKeysCacheService.getPayload(any(OrganizationRecord.class)))
        .thenReturn(Optional.of(new JwksPayloadDto(
            new com.nimbusds.jose.jwk.JWKSet(),
            new com.nimbusds.jose.jwk.JWKSet(),
            JwksPayloadDto.KeyNames.empty())));
  }

  private FederationEntity createFederationEntity() {
    return new FederationEntity().entityIdentifier("https://www.pm.se/oidf/ta/" + UUID.randomUUID());
  }

  /**
   * An entity identifier under the ENA tenant's entity prefix, which is derived from that tenant's own
   * base_url rather than the Swedenconnect org_base_url_overrides entry.
   */
  private FederationEntity createEnaFederationEntity() {
    return new FederationEntity().entityIdentifier(
        "https://registry.ena.se/oidf/" + JwtTestUtils.OrganisationType.PM.orgId + "/ta/" + UUID.randomUUID());
  }

  @Test
  void testCreateFederationEntityWithAutoGeneratedId() {
    // Arrange
    final FederationEntity input = createFederationEntity();

    // Act
    final FederationEntity created = this.entitiesApi.createFederationEntity(TENANT, JwtTestUtils.OrganisationType.PM.orgId, input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getEntityId()).isNotNull();
    assertThat(created.getEntityIdentifier()).isEqualTo(input.getEntityIdentifier());
  }

  @Test
  void testCreateFederationEntityConstraintError() {
    final FederationEntity input = createFederationEntity();


    // Act
    final FederationEntity created = this.entitiesApi.createFederationEntity(TENANT, JwtTestUtils.OrganisationType.PM.orgId, input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getEntityId()).isNotNull();
    assertThat(created.getEntityIdentifier()).isEqualTo(input.getEntityIdentifier());
    assertThatThrownBy(() -> this.entitiesApi.createFederationEntity(TENANT, JwtTestUtils.OrganisationType.PM.orgId, input))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException restException = (RestClientResponseException) exception;
          assertThat(restException.getStatusCode().value()).isEqualTo(400);
        });
  }

  @Test
  void testCreateFederationEntityWithSpecifiedId() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final FederationEntity input = createFederationEntity();


    // Act
    final FederationEntity created = this.entitiesApi.createFederationEntityWithId(TENANT, JwtTestUtils.OrganisationType.PM.orgId, entityId, input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getEntityId()).isEqualTo(entityId);
  }

  @Test
  void testGetFederationEntity() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final FederationEntity input = createFederationEntity();

    this.entitiesApi.createFederationEntityWithId(TENANT, JwtTestUtils.OrganisationType.PM.orgId, entityId, input);

    // Act
    final FederationEntityWithModules retrieved = this.entitiesApi.getFederationEntity(TENANT, JwtTestUtils.OrganisationType.PM.orgId, entityId, false);

    // Assert
    assertThat(retrieved).isNotNull();
    assertThat(retrieved.getEntityId()).isEqualTo(entityId);
  }

  @Test
  void testUpdateFederationEntity() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final FederationEntity createInput = createFederationEntity();

    this.entitiesApi.createFederationEntityWithId(TENANT, JwtTestUtils.OrganisationType.PM.orgId, entityId, createInput);

    final FederationEntity updateInput = createFederationEntity();

    // Act
    final FederationEntity updated = this.entitiesApi.updateFederationEntity(TENANT, JwtTestUtils.OrganisationType.PM.orgId, entityId, updateInput);

    // Assert
    assertThat(updated).isNotNull();
    assertThat(updated.getEntityIdentifier()).isEqualTo(updateInput.getEntityIdentifier());
  }

  @Test
  void testDeleteFederationEntity() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final FederationEntity input = createFederationEntity();

    this.entitiesApi.createFederationEntityWithId(TENANT, JwtTestUtils.OrganisationType.PM.orgId, entityId, input);

    // Verify it exists
    final FederationEntityWithModules beforeDelete = this.entitiesApi.getFederationEntity(TENANT, JwtTestUtils.OrganisationType.PM.orgId, entityId, false);
    assertThat(beforeDelete).isNotNull();

    // Act
    this.entitiesApi.deleteFederationEntity(TENANT, JwtTestUtils.OrganisationType.PM.orgId, entityId);

    // Assert
    assertThatThrownBy(() -> this.entitiesApi.getFederationEntity(TENANT, JwtTestUtils.OrganisationType.PM.orgId, entityId, false))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException restException = (RestClientResponseException) exception;
          assertThat(restException.getStatusCode().value()).isEqualTo(404);
        });
  }

  // -------------------------------------------------------------------------
  // Scope-based access-token flow (no org_rights claim)
  // -------------------------------------------------------------------------

  @Test
  @DisplayName("A scope-only bearer token (no org_rights claim) is granted access through the full stack")
  void testAccessGrantedViaScopeOnlyToken() {
    final ApiClient scopeApiClient = new ApiClient();
    scopeApiClient.setBasePath("http://localhost:" + this.port);
    scopeApiClient.setBearerToken(
        this.jwtTestUtils.createScopeJwt(JwtTestUtils.OrganisationType.PM, "swedenconnect", "admin"));
    final EntitiesApi scopeEntitiesApi = new EntitiesApi(scopeApiClient);

    final FederationEntity created = scopeEntitiesApi.createFederationEntity(
        TENANT, JwtTestUtils.OrganisationType.PM.orgId, createFederationEntity());

    assertThat(created).isNotNull();
    assertThat(created.getEntityId()).isNotNull();
  }

  @Test
  @DisplayName("A bearer token with a mismatched aud claim is rejected with 401")
  void testTokenWithMismatchedAudienceIsRejected() {
    final ApiClient badAudienceApiClient = new ApiClient();
    badAudienceApiClient.setBasePath("http://localhost:" + this.port);
    badAudienceApiClient.setBearerToken(this.jwtTestUtils.createJwt(
        JwtTestUtils.OrganisationType.PM, "wrong-audience",
        List.of(Map.of("function", "swedenconnect", "right", "admin"))));
    final EntitiesApi badAudienceEntitiesApi = new EntitiesApi(badAudienceApiClient);

    assertThatThrownBy(() -> badAudienceEntitiesApi.createFederationEntity(
        TENANT, JwtTestUtils.OrganisationType.PM.orgId, createFederationEntity()))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException restException = (RestClientResponseException) exception;
          assertThat(restException.getStatusCode().value()).isEqualTo(401);
        });
  }

  @Test
  @DisplayName("A token holding rights on the tenant's second configured function group is granted access "
      + "(Swedenconnect is configured with function_groups: swedenconnect, swedenconnect-secondary)")
  void testAccessGrantedViaSecondConfiguredFunctionGroup() {
    final ApiClient secondaryApiClient = new ApiClient();
    secondaryApiClient.setBasePath("http://localhost:" + this.port);
    secondaryApiClient.setBearerToken(this.jwtTestUtils.createJwt(
        JwtTestUtils.OrganisationType.PM, "swedenconnect-secondary", "admin"));
    final EntitiesApi secondaryEntitiesApi = new EntitiesApi(secondaryApiClient);

    final FederationEntity created = secondaryEntitiesApi.createFederationEntity(
        TENANT, JwtTestUtils.OrganisationType.PM.orgId, createFederationEntity());

    assertThat(created).isNotNull();
    assertThat(created.getEntityId()).isNotNull();
  }

  @Test
  @DisplayName("The same function group backs two tenants: a token holding a right on it is granted access "
      + "under either one (Swedenconnect and ENA both list function_groups: swedenconnect)")
  void testAccessGrantedOnBothTenantsSharingAFunctionGroup() {
    final FederationEntity createdOnSwedenconnect = this.entitiesApi.createFederationEntity(
        TENANT, JwtTestUtils.OrganisationType.PM.orgId, createFederationEntity());
    final FederationEntity createdOnEna = this.entitiesApi.createFederationEntity(
        SHARED_FUNCTION_GROUP_TENANT, JwtTestUtils.OrganisationType.PM.orgId, createEnaFederationEntity());

    assertThat(createdOnSwedenconnect.getEntityId()).isNotNull();
    assertThat(createdOnEna.getEntityId()).isNotNull();
  }

  @Test
  @DisplayName("The entity prefix comes from the tenant in the path, not from the function group: the same "
      + "org and the same function group resolve to a different instance under each tenant")
  void testEntityPrefixFollowsTheTenantNotTheFunctionGroup() {
    // Swedenconnect places org 55555 under its org_base_url_overrides entry, ENA under its own base_url.
    // Both are reached with the very same token, whose only right is on the shared "swedenconnect" group.
    assertThatThrownBy(() -> this.entitiesApi.createFederationEntity(
        SHARED_FUNCTION_GROUP_TENANT, JwtTestUtils.OrganisationType.PM.orgId, createFederationEntity()))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException restException = (RestClientResponseException) exception;
          assertThat(restException.getStatusCode().value()).isEqualTo(400);
          assertThat(restException.getResponseBodyAsString())
              .contains("https://registry.ena.se/oidf/" + JwtTestUtils.OrganisationType.PM.orgId);
        });

    assertThat(this.entitiesApi.createFederationEntity(
        SHARED_FUNCTION_GROUP_TENANT, JwtTestUtils.OrganisationType.PM.orgId, createEnaFederationEntity()))
        .isNotNull();
  }

  @Test
  @DisplayName("A right on a function group backing neither tenant is denied on both")
  void testUnrelatedFunctionGroupIsDeniedOnBothTenants() {
    final ApiClient unrelatedApiClient = new ApiClient();
    unrelatedApiClient.setBasePath("http://localhost:" + this.port);
    unrelatedApiClient.setBearerToken(
        this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.PM, "unrelated-group", "admin"));
    final EntitiesApi unrelatedEntitiesApi = new EntitiesApi(unrelatedApiClient);

    assertThatThrownBy(() -> unrelatedEntitiesApi.createFederationEntity(
        TENANT, JwtTestUtils.OrganisationType.PM.orgId, createFederationEntity()))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> assertThat(
            ((RestClientResponseException) exception).getStatusCode().value()).isEqualTo(403));

    assertThatThrownBy(() -> unrelatedEntitiesApi.createFederationEntity(
        SHARED_FUNCTION_GROUP_TENANT, JwtTestUtils.OrganisationType.PM.orgId, createFederationEntity()))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> assertThat(
            ((RestClientResponseException) exception).getStatusCode().value()).isEqualTo(403));
  }

  @Test
  void testEntityIsolationBetweenOrganizations() {
    // Arrange - Create entity with PM organization
    final UUID entityId = UUID.randomUUID();
    final FederationEntity input = createFederationEntity();

    this.entitiesApi.createFederationEntityWithId(TENANT, JwtTestUtils.OrganisationType.PM.orgId, entityId, input);

    // Act - Try to access with AF organization
    final ApiClient afApiClient = new ApiClient();
    afApiClient.setBasePath("http://localhost:" + this.port);
    afApiClient.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.AF));
    final EntitiesApi afEntitiesApi = new EntitiesApi(afApiClient);

    // Assert - Should not be found
    assertThatThrownBy(() -> afEntitiesApi.getFederationEntity(TENANT, JwtTestUtils.OrganisationType.AF.orgId, entityId, false))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException restException = (RestClientResponseException) exception;
          assertThat(restException.getStatusCode().value()).isEqualTo(404);
        });
  }

  // -------------------------------------------------------------------------
  // Signing key tests
  // -------------------------------------------------------------------------

  @Test
  @DisplayName("Federation entity created with empty signingKeyId list persists and returns the list")
  void testCreateFederationEntityWithEmptySigningKeyId() {
    final FederationEntity input = createFederationEntity().signingKeyId(List.of());

    final FederationEntity created = this.entitiesApi.createFederationEntity(TENANT, JwtTestUtils.OrganisationType.PM.orgId, input);

    assertThat(created.getSigningKeyId()).isEmpty();
  }

  @Test
  @DisplayName("Federation entity created with valid name is persisted and returned")
  void testCreateFederationEntityWithValidSigningKeyId() {
    when(jwksKeysCacheService.getPayload(any(OrganizationRecord.class)))
        .thenReturn(Optional.of(new JwksPayloadDto(
            new com.nimbusds.jose.jwk.JWKSet(),
            new com.nimbusds.jose.jwk.JWKSet(),
            new JwksPayloadDto.KeyNames(List.of("federation:sign-key-1"), List.of()))));

    final FederationEntity created = this.entitiesApi.createFederationEntity(TENANT, JwtTestUtils.OrganisationType.PM.orgId, 
        createFederationEntity().signingKeyId(List.of("federation:sign-key-1")));

    assertThat(created.getSigningKeyId()).containsExactly("federation:sign-key-1");
  }

  @Test
  @DisplayName("Federation entity creation fails when name is not in the allowed key names")
  void testCreateFederationEntityWithInvalidSigningKeyIdFails() {
    when(jwksKeysCacheService.getPayload(any(OrganizationRecord.class)))
        .thenReturn(Optional.of(new JwksPayloadDto(
            new com.nimbusds.jose.jwk.JWKSet(),
            new com.nimbusds.jose.jwk.JWKSet(),
            new JwksPayloadDto.KeyNames(List.of("federation:sign-key-1"), List.of()))));

    final FederationEntity input = createFederationEntity().signingKeyId(List.of("federation:unknown-key"));

    assertThatThrownBy(() -> this.entitiesApi.createFederationEntity(TENANT, JwtTestUtils.OrganisationType.PM.orgId, input))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(e -> assertThat(((RestClientResponseException) e).getStatusCode().value()).isEqualTo(400));
  }

  @Test
  @DisplayName("Federation entity signingKeyId can be updated to a new valid name")
  void testUpdateFederationEntitySigningKeyId() {
    when(jwksKeysCacheService.getPayload(any(OrganizationRecord.class)))
        .thenReturn(Optional.of(new JwksPayloadDto(
            new com.nimbusds.jose.jwk.JWKSet(),
            new com.nimbusds.jose.jwk.JWKSet(),
            new JwksPayloadDto.KeyNames(List.of("federation:key-v1", "federation:key-v2"), List.of()))));

    final UUID entityId = UUID.randomUUID();
    this.entitiesApi.createFederationEntityWithId(TENANT, JwtTestUtils.OrganisationType.PM.orgId, entityId,
        createFederationEntity().signingKeyId(List.of("federation:key-v1")));

    final FederationEntity updated = this.entitiesApi.updateFederationEntity(TENANT, JwtTestUtils.OrganisationType.PM.orgId, entityId,
        createFederationEntity().signingKeyId(List.of("federation:key-v2")));

    assertThat(updated.getSigningKeyId()).containsExactly("federation:key-v2");
  }

  @Test
  @DisplayName("Federation entity signingKeyId can be cleared")
  void testClearFederationEntitySigningKeyId() {
    when(jwksKeysCacheService.getPayload(any(OrganizationRecord.class)))
        .thenReturn(Optional.of(new JwksPayloadDto(
            new com.nimbusds.jose.jwk.JWKSet(),
            new com.nimbusds.jose.jwk.JWKSet(),
            new JwksPayloadDto.KeyNames(List.of("federation:key-to-clear"), List.of()))));

    final UUID entityId = UUID.randomUUID();
    this.entitiesApi.createFederationEntityWithId(TENANT, JwtTestUtils.OrganisationType.PM.orgId, entityId,
        createFederationEntity().signingKeyId(List.of("federation:key-to-clear")));

    final FederationEntity updated = this.entitiesApi.updateFederationEntity(TENANT, JwtTestUtils.OrganisationType.PM.orgId, entityId,
        createFederationEntity().signingKeyId(List.of()));

    assertThat(updated.getSigningKeyId()).isEmpty();
  }

  @Test
  @DisplayName("Update fails when the new name is not in the allowed federation key names")
  void testUpdateFederationEntityWithInvalidSigningKeyIdFails() {
    when(jwksKeysCacheService.getPayload(any(OrganizationRecord.class)))
        .thenReturn(Optional.of(new JwksPayloadDto(
            new com.nimbusds.jose.jwk.JWKSet(),
            new com.nimbusds.jose.jwk.JWKSet(),
            new JwksPayloadDto.KeyNames(List.of("federation:allowed-key"), List.of()))));

    final UUID entityId = UUID.randomUUID();
    this.entitiesApi.createFederationEntityWithId(TENANT, JwtTestUtils.OrganisationType.PM.orgId, entityId,
        createFederationEntity().signingKeyId(List.of("federation:allowed-key")));

    assertThatThrownBy(() -> this.entitiesApi.updateFederationEntity(TENANT, JwtTestUtils.OrganisationType.PM.orgId, entityId,
        createFederationEntity().signingKeyId(List.of("federation:not-allowed-key"))))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(e -> assertThat(((RestClientResponseException) e).getStatusCode().value()).isEqualTo(400));
  }

  @Test
  @DisplayName("Hosted key name is rejected when submitted as federation key name")
  void testFederationEntityRejectHostedKey() {
    when(jwksKeysCacheService.getPayload(any(OrganizationRecord.class)))
        .thenReturn(Optional.of(new JwksPayloadDto(
            new com.nimbusds.jose.jwk.JWKSet(),
            new com.nimbusds.jose.jwk.JWKSet(),
            new JwksPayloadDto.KeyNames(List.of("federation:sign-key-1"), List.of("hosted:sign-key-2")))));

    final FederationEntity input = createFederationEntity().signingKeyId(List.of("hosted:sign-key-2"));

    assertThatThrownBy(() -> this.entitiesApi.createFederationEntity(TENANT, JwtTestUtils.OrganisationType.PM.orgId, input))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(e -> assertThat(((RestClientResponseException) e).getStatusCode().value()).isEqualTo(400));
  }
}

