/*
 * Copyright 2025 Sweden Connect
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package se.swedenconnect.oidf.registry.controller;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.testcontainers.containers.MariaDBContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import se.swedenconnect.oidf.registry.api.ApiClient;
import se.swedenconnect.oidf.registry.api.ApiException;
import se.swedenconnect.oidf.registry.api.EntitiesApi;
import se.swedenconnect.oidf.registry.api.model.FederationEntity;
import se.swedenconnect.oidf.registry.api.model.FederationEntityInput;
import se.swedenconnect.oidf.registry.api.model.HostedEntity;
import se.swedenconnect.oidf.registry.api.model.HostedEntityInput;
import se.swedenconnect.oidf.registry.api.model.SubordinateEntity;
import se.swedenconnect.oidf.registry.api.model.SubordinateEntityInput;
import se.swedenconnect.oidf.registry.auth.HttpBearerAuth;
import se.swedenconnect.oidf.registry.fixture.JwtTestUtils;

import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Integration tests for Entity CRUD operations (Federation, Hosted, Subordinate) using the generated OpenAPI client.
 *
 * @author Per Fredrik Plars
 */
@Slf4j
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Testcontainers
class EntityCRUDIT {

  @Container
  @ServiceConnection
  public static MariaDBContainer<?> database = new MariaDBContainer<>("mariadb:11.2");

  @LocalServerPort
  private int port;

  @Autowired
  private JwtTestUtils jwtTestUtils;

  private EntitiesApi entitiesApi;
  private ApiClient apiClient;

  @BeforeEach
  void setUp() {
    this.apiClient = new ApiClient();
    this.apiClient.setBasePath("http://localhost:" + this.port);

    // Configure authentication
    final HttpBearerAuth bearerAuth = (HttpBearerAuth) this.apiClient.getAuthentication("bearerAuth");
    bearerAuth.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.PM));

    // Configure selected org number
    this.apiClient.addDefaultHeader("selected-org-number", JwtTestUtils.OrganisationType.PM.orgId);

    this.entitiesApi = new EntitiesApi(this.apiClient);
  }

  // ========== Federation Entity Tests ==========

  @Test
  void testCreateFederationEntityWithAutoGeneratedId() throws ApiException {
    // Arrange
    final FederationEntityInput input = new FederationEntityInput()
        .subject("http://www.pm.se/oidf/federation")
        .issuer("http://www.pm.se/oidf/ta")
        .metadata(Map.of("federation_entity", Map.of("organization_name", "PM")));

    // Act
    final FederationEntity created = this.entitiesApi.createFederationEntity(input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getEntityId()).isNotNull();
    assertThat(created.getSubject()).isEqualTo("http://www.pm.se/oidf/federation");
    assertThat(created.getIssuer()).isEqualTo("http://www.pm.se/oidf/ta");
    assertThat(created.getMetadata()).isNotNull();
  }

  @Test
  void testCreateFederationEntityWithSpecifiedId() throws ApiException {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final FederationEntityInput input = new FederationEntityInput()
        .subject("http://www.pm.se/oidf/federation2")
        .issuer("http://www.pm.se/oidf/ta2");

    // Act
    final FederationEntity created = this.entitiesApi.createFederationEntityWithId(entityId, input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getEntityId()).isEqualTo(entityId);
    assertThat(created.getSubject()).isEqualTo("http://www.pm.se/oidf/federation2");
  }

  @Test
  void testGetFederationEntity() throws ApiException {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final FederationEntityInput input = new FederationEntityInput()
        .subject("http://www.pm.se/oidf/federation3")
        .issuer("http://www.pm.se/oidf/ta3");
    this.entitiesApi.createFederationEntityWithId(entityId, input);

    // Act
    final FederationEntity retrieved = this.entitiesApi.getFederationEntity(entityId);

    // Assert
    assertThat(retrieved).isNotNull();
    assertThat(retrieved.getEntityId()).isEqualTo(entityId);
    assertThat(retrieved.getSubject()).isEqualTo("http://www.pm.se/oidf/federation3");
  }

  @Test
  void testUpdateFederationEntity() throws ApiException {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final FederationEntityInput createInput = new FederationEntityInput()
        .subject("http://www.pm.se/oidf/federation4")
        .issuer("http://www.pm.se/oidf/ta4");
    this.entitiesApi.createFederationEntityWithId(entityId, createInput);

    final FederationEntityInput updateInput = new FederationEntityInput()
        .subject("http://www.pm.se/oidf/federation4-updated")
        .issuer("http://www.pm.se/oidf/ta4-updated")
        .metadata(Map.of("updated", true));

    // Act
    final FederationEntity updated = this.entitiesApi.updateFederationEntity(entityId, updateInput);

    // Assert
    assertThat(updated).isNotNull();
    assertThat(updated.getSubject()).isEqualTo("http://www.pm.se/oidf/federation4-updated");
    assertThat(updated.getIssuer()).isEqualTo("http://www.pm.se/oidf/ta4-updated");
  }

  @Test
  void testDeleteFederationEntity() throws ApiException {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final FederationEntityInput input = new FederationEntityInput()
        .subject("http://www.pm.se/oidf/federation5")
        .issuer("http://www.pm.se/oidf/ta5");
    this.entitiesApi.createFederationEntityWithId(entityId, input);

    // Verify it exists
    final FederationEntity beforeDelete = this.entitiesApi.getFederationEntity(entityId);
    assertThat(beforeDelete).isNotNull();

    // Act
    this.entitiesApi.deleteFederationEntity(entityId);

    // Assert
    assertThatThrownBy(() -> this.entitiesApi.getFederationEntity(entityId))
        .isInstanceOf(ApiException.class)
        .satisfies(exception -> {
          final ApiException apiException = (ApiException) exception;
          assertThat(apiException.getCode()).isEqualTo(404);
        });
  }

  // ========== Hosted Entity Tests ==========

  @Test
  void testCreateHostedEntityWithAutoGeneratedId() throws ApiException {
    // Arrange
    final HostedEntityInput input = new HostedEntityInput()
        .subject("http://www.pm.se/oidf/hosted")
        .issuer("http://www.pm.se/oidf/ta")
        .metadata(Map.of("hosted_entity", Map.of("name", "Hosted Entity")));

    // Act
    final HostedEntity created = this.entitiesApi.createHostedEntity(input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getEntityId()).isNotNull();
    assertThat(created.getSubject()).isEqualTo("http://www.pm.se/oidf/hosted");
    assertThat(created.getIssuer()).isEqualTo("http://www.pm.se/oidf/ta");
  }

  @Test
  void testCreateHostedEntityWithSpecifiedId() throws ApiException {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntityInput input = new HostedEntityInput()
        .subject("http://www.pm.se/oidf/hosted2")
        .issuer("http://www.pm.se/oidf/ta2");

    // Act
    final HostedEntity created = this.entitiesApi.createHostedEntityWithId(entityId, input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getEntityId()).isEqualTo(entityId);
    assertThat(created.getSubject()).isEqualTo("http://www.pm.se/oidf/hosted2");
  }

  @Test
  void testGetHostedEntity() throws ApiException {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntityInput input = new HostedEntityInput()
        .subject("http://www.pm.se/oidf/hosted3")
        .issuer("http://www.pm.se/oidf/ta3");
    this.entitiesApi.createHostedEntityWithId(entityId, input);

    // Act
    final HostedEntity retrieved = this.entitiesApi.getHostedEntity(entityId);

    // Assert
    assertThat(retrieved).isNotNull();
    assertThat(retrieved.getEntityId()).isEqualTo(entityId);
    assertThat(retrieved.getSubject()).isEqualTo("http://www.pm.se/oidf/hosted3");
  }

  @Test
  void testUpdateHostedEntity() throws ApiException {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntityInput createInput = new HostedEntityInput()
        .subject("http://www.pm.se/oidf/hosted4")
        .issuer("http://www.pm.se/oidf/ta4");
    this.entitiesApi.createHostedEntityWithId(entityId, createInput);

    final HostedEntityInput updateInput = new HostedEntityInput()
        .subject("http://www.pm.se/oidf/hosted4-updated")
        .issuer("http://www.pm.se/oidf/ta4-updated");

    // Act
    final HostedEntity updated = this.entitiesApi.updateHostedEntity(entityId, updateInput);

    // Assert
    assertThat(updated).isNotNull();
    assertThat(updated.getSubject()).isEqualTo("http://www.pm.se/oidf/hosted4-updated");
  }

  @Test
  void testDeleteHostedEntity() throws ApiException {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntityInput input = new HostedEntityInput()
        .subject("http://www.pm.se/oidf/hosted5")
        .issuer("http://www.pm.se/oidf/ta5");
    this.entitiesApi.createHostedEntityWithId(entityId, input);

    // Verify it exists
    final HostedEntity beforeDelete = this.entitiesApi.getHostedEntity(entityId);
    assertThat(beforeDelete).isNotNull();

    // Act
    this.entitiesApi.deleteHostedEntity(entityId);

    // Assert
    assertThatThrownBy(() -> this.entitiesApi.getHostedEntity(entityId))
        .isInstanceOf(ApiException.class)
        .satisfies(exception -> {
          final ApiException apiException = (ApiException) exception;
          assertThat(apiException.getCode()).isEqualTo(404);
        });
  }

  // ========== Subordinate Entity Tests ==========

  @Test
  void testCreateSubordinateEntityWithAutoGeneratedId() throws ApiException {
    // Arrange
    final SubordinateEntityInput input = new SubordinateEntityInput()
        .subject("http://www.pm.se/oidf/subordinate")
        .issuer("http://www.pm.se/oidf/ta")
        .jwks("{\"keys\":[{\"kty\":\"RSA\",\"n\":\"test\",\"e\":\"AQAB\"}]}");

    // Act
    final SubordinateEntity created = this.entitiesApi.createSubordinateEntity(input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getEntityId()).isNotNull();
    assertThat(created.getSubject()).isEqualTo("http://www.pm.se/oidf/subordinate");
    assertThat(created.getIssuer()).isEqualTo("http://www.pm.se/oidf/ta");
    assertThat(created.getJwks()).isNotNull();
  }

  @Test
  void testCreateSubordinateEntityWithSpecifiedId() throws ApiException {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final SubordinateEntityInput input = new SubordinateEntityInput()
        .subject("http://www.pm.se/oidf/subordinate2")
        .issuer("http://www.pm.se/oidf/ta2")
        .jwks("{\"keys\":[]}");

    // Act
    final SubordinateEntity created = this.entitiesApi.createSubordinateEntityWithId(entityId, input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getEntityId()).isEqualTo(entityId);
    assertThat(created.getSubject()).isEqualTo("http://www.pm.se/oidf/subordinate2");
  }

  @Test
  void testGetSubordinateEntity() throws ApiException {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final SubordinateEntityInput input = new SubordinateEntityInput()
        .subject("http://www.pm.se/oidf/subordinate3")
        .issuer("http://www.pm.se/oidf/ta3")
        .jwks("{\"keys\":[{\"kty\":\"EC\"}]}");
    this.entitiesApi.createSubordinateEntityWithId(entityId, input);

    // Act
    final SubordinateEntity retrieved = this.entitiesApi.getSubordinateEntity(entityId);

    // Assert
    assertThat(retrieved).isNotNull();
    assertThat(retrieved.getEntityId()).isEqualTo(entityId);
    assertThat(retrieved.getSubject()).isEqualTo("http://www.pm.se/oidf/subordinate3");
    assertThat(retrieved.getJwks()).isNotNull();
  }

  @Test
  void testUpdateSubordinateEntity() throws ApiException {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final SubordinateEntityInput createInput = new SubordinateEntityInput()
        .subject("http://www.pm.se/oidf/subordinate4")
        .issuer("http://www.pm.se/oidf/ta4")
        .jwks("{\"keys\":[]}");
    this.entitiesApi.createSubordinateEntityWithId(entityId, createInput);

    final SubordinateEntityInput updateInput = new SubordinateEntityInput()
        .subject("http://www.pm.se/oidf/subordinate4-updated")
        .issuer("http://www.pm.se/oidf/ta4-updated")
        .jwks("{\"keys\":[{\"kty\":\"RSA\"}]}");

    // Act
    final SubordinateEntity updated = this.entitiesApi.updateSubordinateEntity(entityId, updateInput);

    // Assert
    assertThat(updated).isNotNull();
    assertThat(updated.getSubject()).isEqualTo("http://www.pm.se/oidf/subordinate4-updated");
    assertThat(updated.getJwks()).contains("RSA");
  }

  @Test
  void testDeleteSubordinateEntity() throws ApiException {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final SubordinateEntityInput input = new SubordinateEntityInput()
        .subject("http://www.pm.se/oidf/subordinate5")
        .issuer("http://www.pm.se/oidf/ta5")
        .jwks("{\"keys\":[]}");
    this.entitiesApi.createSubordinateEntityWithId(entityId, input);

    // Verify it exists
    final SubordinateEntity beforeDelete = this.entitiesApi.getSubordinateEntity(entityId);
    assertThat(beforeDelete).isNotNull();

    // Act
    this.entitiesApi.deleteSubordinateEntity(entityId);

    // Assert
    assertThatThrownBy(() -> this.entitiesApi.getSubordinateEntity(entityId))
        .isInstanceOf(ApiException.class)
        .satisfies(exception -> {
          final ApiException apiException = (ApiException) exception;
          assertThat(apiException.getCode()).isEqualTo(404);
        });
  }

  @Test
  void testEntityIsolationBetweenOrganizations() throws ApiException {
    // Arrange - Create entity with PM organization
    final UUID entityId = UUID.randomUUID();
    final FederationEntityInput input = new FederationEntityInput()
        .subject("http://www.pm.se/oidf/pm-entity")
        .issuer("http://www.pm.se/oidf/ta");
    this.entitiesApi.createFederationEntityWithId(entityId, input);

    // Act - Try to access with AF organization
    final ApiClient afApiClient = new ApiClient();
    afApiClient.setBasePath("http://localhost:" + this.port);
    final HttpBearerAuth afBearerAuth = (HttpBearerAuth) afApiClient.getAuthentication("bearerAuth");
    afBearerAuth.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.AF));
    afApiClient.addDefaultHeader("selected-org-number", JwtTestUtils.OrganisationType.AF.orgId);
    final EntitiesApi afEntitiesApi = new EntitiesApi(afApiClient);

    // Assert - Should not be found
    assertThatThrownBy(() -> afEntitiesApi.getFederationEntity(entityId))
        .isInstanceOf(ApiException.class)
        .satisfies(exception -> {
          final ApiException apiException = (ApiException) exception;
          assertThat(apiException.getCode()).isEqualTo(404);
        });
  }
}

