/*
 * Copyright 2026 Sweden Connect
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package se.swedenconnect.oidf.registry.controller;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.web.client.RestClientResponseException;
import org.testcontainers.containers.MariaDBContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import se.swedenconnect.oidf.registry.ApiClient;
import se.swedenconnect.oidf.registry.api.EntitiesApi;
import se.swedenconnect.oidf.registry.api.model.FederationEntity;
import se.swedenconnect.oidf.registry.api.model.FederationEntityWithModules;
import se.swedenconnect.oidf.registry.fixture.JwtTestUtils;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Integration tests for Entity CRUD operations (Federation, Hosted, Subordinate) using the generated OpenAPI client.
 *
 * @author Per Fredrik Plars
 */
@Slf4j
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Testcontainers
class EntityCRUDIT {

  @Container
  @ServiceConnection
  public static MariaDBContainer<?> database = new MariaDBContainer<>("mariadb:11.2");

  @LocalServerPort
  private int port;

  @Autowired
  private JwtTestUtils jwtTestUtils;

  private EntitiesApi entitiesApi;


  @BeforeEach
  void setUp() {
    final ApiClient apiClient = new ApiClient();
    apiClient.setBasePath("http://localhost:" + this.port);

    // Configure authentication
    apiClient.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.PM));
    apiClient.setApiKey(JwtTestUtils.OrganisationType.PM.orgId);

    entitiesApi = new EntitiesApi(apiClient);
  }

  private FederationEntity createFederationEntity() {
    return new FederationEntity().entityIdentifier("https://www.pm.se/oidf/ta/" + UUID.randomUUID());
  }

  @Test
  void testCreateFederationEntityWithAutoGeneratedId() {
    // Arrange
    final FederationEntity input = createFederationEntity();

    // Act
    final FederationEntity created = this.entitiesApi.createFederationEntity(input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getEntityId()).isNotNull();
    assertThat(created.getEntityIdentifier()).isEqualTo(input.getEntityIdentifier());
  }

  @Test
  void testCreateFederationEntityConstraintError() {
    final FederationEntity input = createFederationEntity();


    // Act
    final FederationEntity created = this.entitiesApi.createFederationEntity(input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getEntityId()).isNotNull();
    assertThat(created.getEntityIdentifier()).isEqualTo(input.getEntityIdentifier());
    assertThatThrownBy(() -> this.entitiesApi.createFederationEntity(input))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException restException = (RestClientResponseException) exception;
          assertThat(restException.getStatusCode().value()).isEqualTo(400);
        });
  }

  @Test
  void testCreateFederationEntityWithSpecifiedId() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final FederationEntity input = createFederationEntity();


    // Act
    final FederationEntity created = this.entitiesApi.createFederationEntityWithId(entityId, input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getEntityId()).isEqualTo(entityId);
  }

  @Test
  void testGetFederationEntity() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final FederationEntity input = createFederationEntity();

    this.entitiesApi.createFederationEntityWithId(entityId, input);

    // Act
    final FederationEntityWithModules retrieved = this.entitiesApi.getFederationEntity(entityId, false);

    // Assert
    assertThat(retrieved).isNotNull();
    assertThat(retrieved.getEntityId()).isEqualTo(entityId);
  }

  @Test
  void testUpdateFederationEntity() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final FederationEntity createInput = createFederationEntity();

    this.entitiesApi.createFederationEntityWithId(entityId, createInput);

    final FederationEntity updateInput = createFederationEntity();

    // Act
    final FederationEntity updated = this.entitiesApi.updateFederationEntity(entityId, updateInput);

    // Assert
    assertThat(updated).isNotNull();
    assertThat(updated.getEntityIdentifier()).isEqualTo(updateInput.getEntityIdentifier());
  }

  @Test
  void testDeleteFederationEntity() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final FederationEntity input = createFederationEntity();

    this.entitiesApi.createFederationEntityWithId(entityId, input);

    // Verify it exists
    final FederationEntityWithModules beforeDelete = this.entitiesApi.getFederationEntity(entityId, false);
    assertThat(beforeDelete).isNotNull();

    // Act
    this.entitiesApi.deleteFederationEntity(entityId);

    // Assert
    assertThatThrownBy(() -> this.entitiesApi.getFederationEntity(entityId, false))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException restException = (RestClientResponseException) exception;
          assertThat(restException.getStatusCode().value()).isEqualTo(404);
        });
  }

  @Test
  void testEntityIsolationBetweenOrganizations() {
    // Arrange - Create entity with PM organization
    final UUID entityId = UUID.randomUUID();
    final FederationEntity input = createFederationEntity();

    this.entitiesApi.createFederationEntityWithId(entityId, input);

    // Act - Try to access with AF organization
    final ApiClient afApiClient = new ApiClient();
    afApiClient.setBasePath("http://localhost:" + this.port);
    afApiClient.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.AF));
    afApiClient.setApiKey(JwtTestUtils.OrganisationType.AF.orgId);
    final EntitiesApi afEntitiesApi = new EntitiesApi(afApiClient);

    // Assert - Should not be found
    assertThatThrownBy(() -> afEntitiesApi.getFederationEntity(entityId, false))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException restException = (RestClientResponseException) exception;
          assertThat(restException.getStatusCode().value()).isEqualTo(404);
        });
  }
}

