/*
 * Copyright 2026 Sweden Connect
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package se.swedenconnect.oidf.registry.controller;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.web.client.RestClientResponseException;
import org.testcontainers.containers.MariaDBContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import se.swedenconnect.oidf.registry.ApiClient;
import se.swedenconnect.oidf.registry.api.EntitiesApi;
import se.swedenconnect.oidf.registry.api.model.HostedEntity;
import se.swedenconnect.oidf.registry.fixture.JwtTestUtils;

import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Integration tests for Entity CRUD operations (Federation, Hosted, Subordinate) using the generated OpenAPI client.
 *
 * @author Per Fredrik Plars
 */
@Slf4j
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Testcontainers
class EntityHostedEntityCRUDIT {

  @Container
  @ServiceConnection
  public static MariaDBContainer<?> database = new MariaDBContainer<>("mariadb:11.2");

  @LocalServerPort
  private int port;

  @Autowired
  private JwtTestUtils jwtTestUtils;

  private EntitiesApi entitiesApi;

  @BeforeEach
  void setUp() {
    final ApiClient apiClient = new ApiClient();
    apiClient.setBasePath("http://localhost:" + this.port);

    // Configure authentication
    apiClient.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.PM));
    apiClient.setApiKey(JwtTestUtils.OrganisationType.PM.orgId);

    entitiesApi = new EntitiesApi(apiClient);
  }

  // ========== Hosted Entity Tests ==========

  @Test
  void testCreateHostedEntityWithAutoGeneratedId() {
    // Arrange
    final HostedEntity input = new HostedEntity()
        .entityIdentifier("https://www.pm.se/oidf/ta")
        .metadata(Map.of("hosted_entity", Map.of("name", "Hosted Entity")));

    // Act
    final HostedEntity created = this.entitiesApi.createHostedEntity(input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getEntityId()).isNotNull();
    assertThat(created.getEntityIdentifier()).isEqualTo("https://www.pm.se/oidf/ta");
  }

  @Test
  void testCreateHostedEntityWithSpecifiedId() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntity input = new HostedEntity()
        .entityIdentifier("https://www.pm.se/oidf/ta2");

    // Act
    final HostedEntity created = this.entitiesApi.createHostedEntityWithId(entityId, input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getEntityId()).isEqualTo(entityId);
  }

  @Test
  void testGetHostedEntity() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntity input = new HostedEntity()
        .entityIdentifier("https://www.pm.se/oidf/ta3");
    this.entitiesApi.createHostedEntityWithId(entityId, input);

    // Act
    final HostedEntity retrieved = this.entitiesApi.getHostedEntity(entityId);

    // Assert
    assertThat(retrieved).isNotNull();
    assertThat(retrieved.getEntityId()).isEqualTo(entityId);
  }

  @Test
  void testUpdateHostedEntity() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntity createInput = new HostedEntity()
        .entityIdentifier("https://www.pm.se/oidf/ta4");
    this.entitiesApi.createHostedEntityWithId(entityId, createInput);

    final HostedEntity updateInput = new HostedEntity()
        .entityIdentifier("https://www.pm.se/oidf/ta4-updated");

    // Act
    final HostedEntity updated = this.entitiesApi.updateHostedEntity(entityId, updateInput);

    // Assert
    assertThat(updated).isNotNull();
  }

  @Test
  void testDeleteHostedEntity() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntity input = new HostedEntity()
        .entityIdentifier("https://www.pm.se/oidf/ta5");
    this.entitiesApi.createHostedEntityWithId(entityId, input);

    // Verify it exists
    final HostedEntity beforeDelete = this.entitiesApi.getHostedEntity(entityId);
    assertThat(beforeDelete).isNotNull();

    // Act
    this.entitiesApi.deleteHostedEntity(entityId);

    // Assert
    assertThatThrownBy(() -> this.entitiesApi.getHostedEntity(entityId))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException restException = (RestClientResponseException) exception;
          assertThat(restException.getStatusCode().value()).isEqualTo(404);
        });
  }

  @Test
  void testCreateHostedEntityWithEcLocationAutoResolve() {
    // Arrange
    final HostedEntity input = new HostedEntity()
        .entityIdentifier("https://www.telia.se/oidf/ta")
        .metadata(Map.of("hosted_entity", Map.of("name", "Hosted Entity")));
    // Act
    final HostedEntity created = this.entitiesApi.createHostedEntity(input);
    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getEffectiveEcLocation()).isNotNull();
    assertThat(created.getEntityId()).isNotNull();
    assertThat(created.getEntityIdentifier()).isEqualTo(input.getEntityIdentifier());

  }

}

