/*
 * Copyright 2025 Sweden Connect
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package se.swedenconnect.oidf.registry.controller;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.web.client.RestClientResponseException;
import org.testcontainers.containers.MariaDBContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import se.swedenconnect.oidf.registry.ApiClient;
import se.swedenconnect.oidf.registry.api.EntitiesApi;
import se.swedenconnect.oidf.registry.api.ModulesApi;
import se.swedenconnect.oidf.registry.api.model.FederationEntity;
import se.swedenconnect.oidf.registry.api.model.HostedEntity;
import se.swedenconnect.oidf.registry.api.model.Resolver;
import se.swedenconnect.oidf.registry.api.model.TrustAnchor;
import se.swedenconnect.oidf.registry.api.model.Trustmark;
import se.swedenconnect.oidf.registry.fixture.JwtTestUtils;

import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Integration tests for Module CRUD operations (TrustAnchor, Resolver, Trustmark) using the generated OpenAPI client.
 *
 * @author Per Fredrik Plars
 */
@Slf4j
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Testcontainers
class ModuleCRUDIT {

  @Container
  @ServiceConnection
  public static MariaDBContainer<?> database = new MariaDBContainer<>("mariadb:11.2");

  @LocalServerPort
  private int port;

  @Autowired
  private JwtTestUtils jwtTestUtils;

  private ModulesApi modulesApi;
  private EntitiesApi entitiesApi;
  private ApiClient apiClient;

  @BeforeEach
  void setUp() {
    this.apiClient = new ApiClient();
    this.apiClient.setBasePath("http://localhost:" + this.port);

    // Configure authentication
    this.apiClient.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.PM));
    this.apiClient.setApiKey(JwtTestUtils.OrganisationType.PM.orgId);

    this.modulesApi = new ModulesApi(this.apiClient);
    this.entitiesApi = new EntitiesApi(this.apiClient);
  }

  // ========== TrustAnchor Tests ==========

  @Test
  void testCreateTrustAnchorWithAutoGeneratedId() {
    // Arrange - Create a hosted entity first (required for trust anchor)
    final UUID entityId = UUID.randomUUID();
    final FederationEntity entityInput = new FederationEntity()
        .subject("http://www.pm.se/oidf/ta-entity")
        .issuer("http://www.pm.se/oidf/ta-entity");
    this.entitiesApi.createFederationEntityWithId(entityId, entityInput);

    final TrustAnchor input = new TrustAnchor()
        .entityId(entityId)
        .active(true)
        .trustMarkIssuers(List.of("http://www.pm.se/oidf/tmi1", "http://www.pm.se/oidf/tmi2"));

    // Act
    final TrustAnchor created = this.modulesApi.createTrustAnchor(input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getModuleId()).isNotNull();
    assertThat(created.getEntityId()).isEqualTo("http://www.pm.se/oidf/ta-entity");
    assertThat(created.getActive()).isTrue();
    assertThat(created.getTrustMarkIssuers()).contains("http://www.pm.se/oidf/tmi1", "http://www.pm.se/oidf/tmi2");
  }

  @Test
  void testCreateTrustAnchorWithSpecifiedId() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntity entityInput = new HostedEntity()
        .subject("http://www.pm.se/oidf/ta-entity2")
        .issuer("http://www.pm.se/oidf/ta-entity2");
    this.entitiesApi.createHostedEntityWithId(entityId, entityInput);

    final UUID moduleId = UUID.randomUUID();
    final TrustAnchor input = new TrustAnchor()
        .entityId(entityId)
        .active(false);

    // Act
    final TrustAnchor created = this.modulesApi.createTrustAnchorWithId(moduleId, input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getModuleId()).isEqualTo(moduleId);
    assertThat(created.getActive()).isFalse();
  }

  @Test
  void testGetTrustAnchor() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntity entityInput = new HostedEntity()
        .subject("http://www.pm.se/oidf/ta-entity3")
        .issuer("http://www.pm.se/oidf/ta-entity3");
    this.entitiesApi.createHostedEntityWithId(entityId, entityInput);

    final UUID moduleId = UUID.randomUUID();
    final TrustAnchor input = new TrustAnchor()
        .entityId(entityId)
        .active(true);
    this.modulesApi.createTrustAnchorWithId(moduleId, input);

    // Act
    final TrustAnchor retrieved = this.modulesApi.getTrustAnchor(moduleId);

    // Assert
    assertThat(retrieved).isNotNull();
    assertThat(retrieved.getModuleId()).isEqualTo(moduleId);
    assertThat(retrieved.getEntityId()).isEqualTo("http://www.pm.se/oidf/ta-entity3");
  }

  @Test
  void testUpdateTrustAnchor() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntity entityInput = new HostedEntity()
        .subject("http://www.pm.se/oidf/ta-entity4")
        .issuer("http://www.pm.se/oidf/ta-entity4");
    this.entitiesApi.createHostedEntityWithId(entityId, entityInput);

    final UUID moduleId = UUID.randomUUID();
    final TrustAnchor createInput = new TrustAnchor()
        .entityId(entityId)
        .active(true);
    this.modulesApi.createTrustAnchorWithId(moduleId, createInput);

    final TrustAnchor updateInput = new TrustAnchor()
        .entityId(entityId)
        .active(false)
        .trustMarkIssuers(List.of("http://www.pm.se/oidf/tmi-updated"));

    // Act
    final TrustAnchor updated = this.modulesApi.updateTrustAnchor(moduleId, updateInput);

    // Assert
    assertThat(updated).isNotNull();
    assertThat(updated.getActive()).isFalse();
    assertThat(updated.getTrustMarkIssuers()).contains("http://www.pm.se/oidf/tmi-updated");
  }

  @Test
  void testDeleteTrustAnchor() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntity entityInput = new HostedEntity()
        .subject("http://www.pm.se/oidf/ta-entity5")
        .issuer("http://www.pm.se/oidf/ta-entity5");
    this.entitiesApi.createHostedEntityWithId(entityId, entityInput);

    final UUID moduleId = UUID.randomUUID();
    final TrustAnchor input = new TrustAnchor()
        .entityId(entityId)
        .active(true);
    this.modulesApi.createTrustAnchorWithId(moduleId, input);

    // Verify it exists
    final TrustAnchor beforeDelete = this.modulesApi.getTrustAnchor(moduleId);
    assertThat(beforeDelete).isNotNull();

    // Act
    this.modulesApi.deleteTrustAnchor(moduleId);

    // Assert
    assertThatThrownBy(() -> this.modulesApi.getTrustAnchor(moduleId))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException apiException = (RestClientResponseException) exception;
          assertThat(apiException.getStatusCode().value()).isEqualTo(404);
        });
  }

  // ========== Resolver Tests ==========

  @Test
  void testCreateResolverWithAutoGeneratedId() {
    // Arrange - Create a hosted entity first
    final UUID entityId = UUID.randomUUID();
    final HostedEntity entityInput = new HostedEntity()
        .subject("http://www.pm.se/oidf/resolver-entity")
        .issuer("http://www.pm.se/oidf/resolver-entity");
    this.entitiesApi.createHostedEntityWithId(entityId, entityInput);

    final Resolver input = new Resolver()
        .entityId(entityId)
        .active(true)
        .resolveResponseDuration("PT1H")
        .trustAnchor("http://www.pm.se/oidf/ta")
        .trustedKeys("{\"keys\":[{\"kty\":\"RSA\"}]}")
        .stepRetryDuration("PT30M");

    // Act
    final Resolver created = this.modulesApi.createResolver(input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getModuleId()).isNotNull();
    assertThat(created.getEntityId()).isEqualTo("http://www.pm.se/oidf/resolver-entity");
    assertThat(created.getActive()).isTrue();
    assertThat(created.getResolveResponseDuration()).isEqualTo("PT1H");
    assertThat(created.getTrustAnchor()).isEqualTo("http://www.pm.se/oidf/ta");
  }

  @Test
  void testCreateResolverWithSpecifiedId() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntity entityInput = new HostedEntity()
        .subject("http://www.pm.se/oidf/resolver-entity2")
        .issuer("http://www.pm.se/oidf/resolver-entity2");
    this.entitiesApi.createHostedEntityWithId(entityId, entityInput);

    final UUID moduleId = UUID.randomUUID();
    final Resolver input = new Resolver()
        .entityId(entityId)
        .active(false)
        .resolveResponseDuration("PT2H");

    // Act
    final Resolver created = this.modulesApi.createResolverWithId(moduleId, input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getModuleId()).isEqualTo(moduleId);
    assertThat(created.getActive()).isFalse();
  }

  @Test
  void testGetResolver() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntity entityInput = new HostedEntity()
        .subject("http://www.pm.se/oidf/resolver-entity3")
        .issuer("http://www.pm.se/oidf/resolver-entity3");
    this.entitiesApi.createHostedEntityWithId(entityId, entityInput);

    final UUID moduleId = UUID.randomUUID();
    final Resolver input = new Resolver()
        .entityId(entityId)
        .active(true)
        .resolveResponseDuration("PT1H");
    this.modulesApi.createResolverWithId(moduleId, input);

    // Act
    final Resolver retrieved = this.modulesApi.getResolver(moduleId);

    // Assert
    assertThat(retrieved).isNotNull();
    assertThat(retrieved.getModuleId()).isEqualTo(moduleId);
    assertThat(retrieved.getEntityId()).isEqualTo("http://www.pm.se/oidf/resolver-entity3");
  }

  @Test
  void testUpdateResolver() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntity entityInput = new HostedEntity()
        .subject("http://www.pm.se/oidf/resolver-entity4")
        .issuer("http://www.pm.se/oidf/resolver-entity4");
    this.entitiesApi.createHostedEntityWithId(entityId, entityInput);

    final UUID moduleId = UUID.randomUUID();
    final Resolver createInput = new Resolver()
        .entityId(entityId)
        .active(true)
        .resolveResponseDuration("PT1H");
    this.modulesApi.createResolverWithId(moduleId, createInput);

    final Resolver updateInput = new Resolver()
        .entityId(entityId)
        .active(false)
        .resolveResponseDuration("PT3H")
        .trustAnchor("http://www.pm.se/oidf/ta-updated");

    // Act
    final Resolver updated = this.modulesApi.updateResolver(moduleId, updateInput);

    // Assert
    assertThat(updated).isNotNull();
    assertThat(updated.getActive()).isFalse();
    assertThat(updated.getResolveResponseDuration()).isEqualTo("PT3H");
    assertThat(updated.getTrustAnchor()).isEqualTo("http://www.pm.se/oidf/ta-updated");
  }

  @Test
  void testDeleteResolver() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntity entityInput = new HostedEntity()
        .subject("http://www.pm.se/oidf/resolver-entity5")
        .issuer("http://www.pm.se/oidf/resolver-entity5");
    this.entitiesApi.createHostedEntityWithId(entityId, entityInput);

    final UUID moduleId = UUID.randomUUID();
    final Resolver input = new Resolver()
        .entityId(entityId)
        .active(true);
    this.modulesApi.createResolverWithId(moduleId, input);

    // Verify it exists
    final Resolver beforeDelete = this.modulesApi.getResolver(moduleId);
    assertThat(beforeDelete).isNotNull();

    // Act
    this.modulesApi.deleteResolver(moduleId);

    // Assert
    assertThatThrownBy(() -> this.modulesApi.getResolver(moduleId))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException apiException = (RestClientResponseException) exception;
          assertThat(apiException.getStatusCode().value()).isEqualTo(404);
        });
  }

  // ========== Trustmark Tests ==========

  @Test
  void testCreateTrustmarkWithAutoGeneratedId() {
    // Arrange - Create a trust anchor first (required for trustmark)
    final UUID entityId = UUID.randomUUID();
    final HostedEntity entityInput = new HostedEntity()
        .subject("http://www.pm.se/oidf/tmi-entity")
        .issuer("http://www.pm.se/oidf/tmi-entity");
    this.entitiesApi.createHostedEntityWithId(entityId, entityInput);

    final UUID taModuleId = UUID.randomUUID();
    final TrustAnchor taInput = new TrustAnchor()
        .entityId(entityId)
        .active(true);
    this.modulesApi.createTrustAnchorWithId(taModuleId, taInput);

    final Trustmark input = new Trustmark()
        .trustmarkissuerId("http://www.pm.se/oidf/tmi-entity")
        .trustMarkEntityId("http://www.pm.se/oidf/trustmark")
        .logoUri("http://www.pm.se/logo.png")
        .refUri("http://www.pm.se/ref")
        .delegation("eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...");

    // Act
    final Trustmark created = this.modulesApi.createTrustmark(input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getTrustmarkId()).isNotNull();
    assertThat(created.getTrustmarkissuerId()).isEqualTo("http://www.pm.se/oidf/tmi-entity");
    assertThat(created.getTrustMarkEntityId()).isEqualTo("http://www.pm.se/oidf/trustmark");
    assertThat(created.getLogoUri()).isEqualTo("http://www.pm.se/logo.png");
  }

  @Test
  void testCreateTrustmarkWithSpecifiedId() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntity entityInput = new HostedEntity()
        .subject("http://www.pm.se/oidf/tmi-entity2")
        .issuer("http://www.pm.se/oidf/tmi-entity2");
    this.entitiesApi.createHostedEntityWithId(entityId, entityInput);

    final UUID taModuleId = UUID.randomUUID();
    final TrustAnchor taInput = new TrustAnchor()
        .entityId(entityId)
        .active(true);
    this.modulesApi.createTrustAnchorWithId(taModuleId, taInput);

    final UUID trustmarkId = UUID.randomUUID();
    final Trustmark input = new Trustmark()
        .trustmarkissuerId("http://www.pm.se/oidf/tmi-entity2")
        .trustMarkEntityId("http://www.pm.se/oidf/trustmark2");

    // Act
    final Trustmark created = this.modulesApi.createTrustmarkWithId(trustmarkId, input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getTrustmarkId()).isEqualTo(trustmarkId);
    assertThat(created.getTrustMarkEntityId()).isEqualTo("http://www.pm.se/oidf/trustmark2");
  }

  @Test
  void testGetTrustmark() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntity entityInput = new HostedEntity()
        .subject("http://www.pm.se/oidf/tmi-entity3")
        .issuer("http://www.pm.se/oidf/tmi-entity3");
    this.entitiesApi.createHostedEntityWithId(entityId, entityInput);

    final UUID taModuleId = UUID.randomUUID();
    final TrustAnchor taInput = new TrustAnchor()
        .entityId(entityId)
        .active(true);
    this.modulesApi.createTrustAnchorWithId(taModuleId, taInput);

    final UUID trustmarkId = UUID.randomUUID();
    final Trustmark input = new Trustmark()
        .trustmarkissuerId("http://www.pm.se/oidf/tmi-entity3")
        .trustMarkEntityId("http://www.pm.se/oidf/trustmark3");
    this.modulesApi.createTrustmarkWithId(trustmarkId, input);

    // Act
    final Trustmark retrieved = this.modulesApi.getTrustmark(trustmarkId);

    // Assert
    assertThat(retrieved).isNotNull();
    assertThat(retrieved.getTrustmarkId()).isEqualTo(trustmarkId);
    assertThat(retrieved.getTrustMarkEntityId()).isEqualTo("http://www.pm.se/oidf/trustmark3");
  }

  @Test
  void testUpdateTrustmark() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntity entityInput = new HostedEntity()
        .subject("http://www.pm.se/oidf/tmi-entity4")
        .issuer("http://www.pm.se/oidf/tmi-entity4");
    this.entitiesApi.createHostedEntityWithId(entityId, entityInput);

    final UUID taModuleId = UUID.randomUUID();
    final TrustAnchor taInput = new TrustAnchor()
        .entityId(entityId)
        .active(true);
    this.modulesApi.createTrustAnchorWithId(taModuleId, taInput);

    final UUID trustmarkId = UUID.randomUUID();
    final Trustmark createInput = new Trustmark()
        .trustmarkissuerId("http://www.pm.se/oidf/tmi-entity4")
        .trustMarkEntityId("http://www.pm.se/oidf/trustmark4");
    this.modulesApi.createTrustmarkWithId(trustmarkId, createInput);

    final Trustmark updateInput = new Trustmark()
        .trustmarkissuerId("http://www.pm.se/oidf/tmi-entity4")
        .trustMarkEntityId("http://www.pm.se/oidf/trustmark4-updated")
        .logoUri("http://www.pm.se/logo-updated.png")
        .refUri("http://www.pm.se/ref-updated");

    // Act
    final Trustmark updated = this.modulesApi.updateTrustmark(trustmarkId, updateInput);

    // Assert
    assertThat(updated).isNotNull();
    assertThat(updated.getTrustMarkEntityId()).isEqualTo("http://www.pm.se/oidf/trustmark4-updated");
    assertThat(updated.getLogoUri()).isEqualTo("http://www.pm.se/logo-updated.png");
  }

  @Test
  void testDeleteTrustmark() {
    // Arrange
    final UUID entityId = UUID.randomUUID();
    final HostedEntity entityInput = new HostedEntity()
        .subject("http://www.pm.se/oidf/tmi-entity5")
        .issuer("http://www.pm.se/oidf/tmi-entity5");
    this.entitiesApi.createHostedEntityWithId(entityId, entityInput);

    final UUID taModuleId = UUID.randomUUID();
    final TrustAnchor taInput = new TrustAnchor()
        .entityId(entityId)
        .active(true);
    this.modulesApi.createTrustAnchorWithId(taModuleId, taInput);

    final UUID trustmarkId = UUID.randomUUID();
    final Trustmark input = new Trustmark()
        .trustmarkissuerId("http://www.pm.se/oidf/tmi-entity5")
        .trustMarkEntityId("http://www.pm.se/oidf/trustmark5");
    this.modulesApi.createTrustmarkWithId(trustmarkId, input);

    // Verify it exists
    final Trustmark beforeDelete = this.modulesApi.getTrustmark(trustmarkId);
    assertThat(beforeDelete).isNotNull();

    // Act
    this.modulesApi.deleteTrustmark(trustmarkId);

    // Assert
    assertThatThrownBy(() -> this.modulesApi.getTrustmark(trustmarkId))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException apiException = (RestClientResponseException) exception;
          assertThat(apiException.getStatusCode().value()).isEqualTo(404);
        });
  }
}

