/*
 * Copyright 2026 Sweden Connect
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package se.swedenconnect.oidf.registry.controller;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.resttestclient.autoconfigure.AutoConfigureRestTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.web.client.RestClientResponseException;
import org.testcontainers.containers.MariaDBContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import se.swedenconnect.oidf.registry.ApiClient;
import se.swedenconnect.oidf.registry.api.PoliciesApi;
import se.swedenconnect.oidf.registry.api.model.Policy;
import se.swedenconnect.oidf.registry.fixture.JwtTestUtils;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Integration tests for Policy CRUD operations using the generated OpenAPI client.
 *
 * @author Per Fredrik Plars
 */
@Slf4j
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Testcontainers
@AutoConfigureRestTestClient
class PolicyCRUDIT {

  @Container
  @ServiceConnection
  public static MariaDBContainer<?> database = new MariaDBContainer<>("mariadb:11.2");

  @LocalServerPort
  private int port;

  @Autowired
  private JwtTestUtils jwtTestUtils;

  private PoliciesApi policiesApi;
  private ApiClient apiClient;

  @BeforeEach
  void setUp() {
    this.apiClient = new ApiClient();
    this.apiClient.setBasePath("http://localhost:" + this.port);

    // Configure authentication
    this.apiClient.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.PM));
    this.apiClient.setApiKey(JwtTestUtils.OrganisationType.PM.orgId);

    this.policiesApi = new PoliciesApi(this.apiClient);
  }

  @Test
  void testCreatePolicyWithAutoGeneratedId() {
    // Arrange
    final Policy input = new Policy()
        .name("Test Policy")
        .policy(Map.of("key", "value"));

    // Act
    final Policy created = this.policiesApi.createPolicy(input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getPolicyId()).isNotNull();
    assertThat(created.getName()).isEqualTo("Test Policy");
    assertThat(created.getPolicy()).isEqualTo(Map.of("key", "value"));
  }

  @Test
  void testCreatePolicyWithSpecifiedId() {
    // Arrange
    final UUID policyId = UUID.randomUUID();
    final Policy input = new Policy()
        .name("Test Policy With ID")
        .policy(Map.of("test", "data"));

    // Act
    final Policy created = this.policiesApi.createPolicyWithId(policyId, input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getPolicyId()).isEqualTo(policyId);
    assertThat(created.getName()).isEqualTo("Test Policy With ID");
    assertThat(created.getPolicy()).isEqualTo(Map.of("test", "data"));
  }

  @Test
  void testGetPolicy() {
    // Arrange
    final UUID policyId = UUID.randomUUID();
    final Policy input = new Policy()
        .name("Policy to Get")
        .policy(Map.of("get", "test"));
    this.policiesApi.createPolicyWithId(policyId, input);

    // Act
    final Policy retrieved = this.policiesApi.getPolicy(policyId);

    // Assert
    assertThat(retrieved).isNotNull();
    assertThat(retrieved.getPolicyId()).isEqualTo(policyId);
    assertThat(retrieved.getName()).isEqualTo("Policy to Get");
    assertThat(retrieved.getPolicy()).isEqualTo(Map.of("get", "test"));
  }

  @Test
  void testGetPolicyNotFound() {
    // Arrange
    final UUID nonExistentId = UUID.randomUUID();

    // Act & Assert
    assertThatThrownBy(() -> this.policiesApi.getPolicy(nonExistentId))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException restException = (RestClientResponseException) exception;
          assertThat(restException.getStatusCode().value()).isEqualTo(404);
        });
  }

  @Test
  void testUpdatePolicy() {
    // Arrange
    final UUID policyId = UUID.randomUUID();
    final Policy createInput = new Policy()
        .name("Original Policy")
        .policy(Map.of("original", "data"));
    this.policiesApi.createPolicyWithId(policyId, createInput);

    final Policy updateInput = new Policy()
        .name("Updated Policy")
        .policy(Map.of("updated", "data"));

    // Act
    final Policy updated = this.policiesApi.updatePolicy(policyId, updateInput);

    // Assert
    assertThat(updated).isNotNull();
    assertThat(updated.getPolicyId()).isEqualTo(policyId);
    assertThat(updated.getName()).isEqualTo("Updated Policy");
    assertThat(updated.getPolicy()).isEqualTo(Map.of("updated", "data"));

    // Verify by getting again
    final Policy retrieved = this.policiesApi.getPolicy(policyId);
    assertThat(retrieved.getName()).isEqualTo("Updated Policy");
  }

  @Test
  void testDeletePolicy() {
    // Arrange
    final UUID policyId = UUID.randomUUID();
    final Policy input = new Policy()
        .name("Policy to Delete")
        .policy(Map.of("delete", "test"));
    this.policiesApi.createPolicyWithId(policyId, input);

    // Verify it exists
    final Policy beforeDelete = this.policiesApi.getPolicy(policyId);
    assertThat(beforeDelete).isNotNull();

    // Act
    this.policiesApi.deletePolicy(policyId);

    // Assert - should not be found
    assertThatThrownBy(() -> this.policiesApi.getPolicy(policyId))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException restException = (RestClientResponseException) exception;
          assertThat(restException.getStatusCode().value()).isEqualTo(404);
        });
  }

  @Test
  void testListPolicies() {
    // Arrange
    final Policy input1 = new Policy()
        .name("Policy 1")
        .policy(Map.of("policy", "1"));
    final Policy input2 = new Policy()
        .name("Policy 2")
        .policy(Map.of("policy", "2"));

    this.policiesApi.createPolicy(input1);
    this.policiesApi.createPolicy(input2);

    // Act
    final List<Policy> policies = this.policiesApi.listPolicies();

    // Assert
    assertThat(policies).isNotNull();
    assertThat(policies.size()).isGreaterThanOrEqualTo(2);
    assertThat(policies).extracting(Policy::getName)
        .contains("Policy 1", "Policy 2");
  }

  @Test
  void testPolicyIsolationBetweenOrganizations() {
    // Arrange - Create policy with PM organization
    final UUID policyId = UUID.randomUUID();
    final Policy input = new Policy()
        .name("PM Policy")
        .policy(Map.of("org", "PM"));
    this.policiesApi.createPolicyWithId(policyId, input);

    // Act - Try to access with AF organization
    final ApiClient afApiClient = new ApiClient();
    afApiClient.setBasePath("http://localhost:" + this.port);
    afApiClient.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.AF));
    afApiClient.setApiKey(JwtTestUtils.OrganisationType.AF.orgId);
    final PoliciesApi afPoliciesApi = new PoliciesApi(afApiClient);

    // Assert - Should not be found
    assertThatThrownBy(() -> afPoliciesApi.getPolicy(policyId))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException restException = (RestClientResponseException) exception;
          assertThat(restException.getStatusCode().value()).isEqualTo(404);
        });
  }

  @Test
  void testPolicyWithComplexJson() {
    // Arrange
    final Map<String, Object> complexPolicy = new HashMap<>();
    complexPolicy.put("version", 1);
    complexPolicy.put("rules", List.of(
        Map.of("type", "allow", "path", "/api/*"),
        Map.of("type", "deny", "path", "/admin/*")
    ));
    complexPolicy.put("metadata", Map.of("created", "2025-01-01", "author", "test"));

    final Policy input = new Policy()
        .name("Complex Policy")
        .policy(complexPolicy);

    // Act
    final Policy created = this.policiesApi.createPolicy(input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getPolicy()).isEqualTo(complexPolicy);
  }
}

