/*
 * Copyright 2026 Sweden Connect
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package se.swedenconnect.oidf.registry.controller;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.resttestclient.autoconfigure.AutoConfigureRestTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.web.client.RestClientResponseException;
import org.testcontainers.containers.MariaDBContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import se.swedenconnect.oidf.registry.ApiClient;
import se.swedenconnect.oidf.registry.api.PoliciesApi;
import se.swedenconnect.oidf.registry.api.model.Policy;
import se.swedenconnect.oidf.registry.fixture.JwtTestUtils;
import se.swedenconnect.oidf.registry.fixture.TestDataOperations;

import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Integration tests for Policy CRUD operations using the generated OpenAPI client.
 *
 * @author Per Fredrik Plars
 */
@Slf4j
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Testcontainers
@AutoConfigureRestTestClient
class PolicyCRUDIT {

  @Container
  @ServiceConnection
  public static MariaDBContainer<?> database = new MariaDBContainer<>("mariadb:11.2");

  @LocalServerPort
  private int port;

  @Autowired
  private JwtTestUtils jwtTestUtils;

  private PoliciesApi policiesApi;
  private ApiClient apiClient;

  final TestDataOperations testDataOperations = new TestDataOperations();

  @BeforeEach
  void setUp() {
    this.apiClient = new ApiClient();
    this.apiClient.setBasePath("http://localhost:" + this.port);

    // Configure authentication
    this.apiClient.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.PM));
    this.apiClient.setApiKey(JwtTestUtils.OrganisationType.PM.orgId);

    this.policiesApi = new PoliciesApi(this.apiClient);
  }

  @Test
  void testCreatePolicyWithAutoGeneratedId() {
    // Arrange
    final Policy input = this.testDataOperations.createPolicy();


    // Act
    final Policy created = this.policiesApi.createPolicy(input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getPolicyId()).isNotNull();
    assertThat(created.getName()).isEqualTo(input.getName());
    assertThat(created.getPolicy()).isEqualTo(this.testDataOperations.createPolicy().getPolicy());
  }

  @Test
  void testCreatePolicyWithSpecifiedId() {
    // Arrange
    final UUID policyId = UUID.randomUUID();
    final Policy input = this.testDataOperations.createPolicy();

    // Act
    final Policy created = this.policiesApi.createPolicyWithId(policyId, input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getPolicyId()).isEqualTo(policyId);
    assertThat(created.getName()).isEqualTo(created.getName());
    assertThat(created.getPolicy()).isEqualTo(this.testDataOperations.createPolicy().getPolicy());
  }

  @Test
  void testGetPolicy() {
    // Arrange
    final UUID policyId = UUID.randomUUID();
    final Policy input = this.testDataOperations.createPolicy();

    this.policiesApi.createPolicyWithId(policyId, input);

    // Act
    final Policy retrieved = this.policiesApi.getPolicy(policyId);

    // Assert
    assertThat(retrieved).isNotNull();
    assertThat(retrieved.getPolicyId()).isEqualTo(policyId);
    assertThat(retrieved.getName()).isEqualTo(input.getName());
    assertThat(input.getPolicy()).isEqualTo(this.testDataOperations.createPolicy().getPolicy());
  }

  @Test
  void testGetPolicyNotFound() {
    // Arrange
    final UUID nonExistentId = UUID.randomUUID();

    // Act & Assert
    assertThatThrownBy(() -> this.policiesApi.getPolicy(nonExistentId))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException restException = (RestClientResponseException) exception;
          assertThat(restException.getStatusCode().value()).isEqualTo(404);
        });
  }

  @Test
  void testUpdatePolicy() {
    // Arrange
    final UUID policyId = UUID.randomUUID();
    final Policy createInput = this.testDataOperations.createPolicy();

    this.policiesApi.createPolicyWithId(policyId, createInput);

    final Policy updateInput = this.testDataOperations.createPolicy();


    // Act
    final Policy updated = this.policiesApi.updatePolicy(policyId, updateInput);

    // Assert
    assertThat(updated).isNotNull();
    assertThat(updated.getPolicyId()).isEqualTo(policyId);
    assertThat(updated.getName()).isEqualTo(updateInput.getName());
    assertThat(updated.getPolicy()).isEqualTo(updateInput.getPolicy());
    assertThat(updated.getPolicy()).isEqualTo(this.testDataOperations.createPolicy().getPolicy());


    // Verify by getting again
    final Policy retrieved = this.policiesApi.getPolicy(policyId);
    assertThat(retrieved.getName()).isEqualTo(updated.getName());
  }

  @Test
  void testDeletePolicy() {
    // Arrange
    final UUID policyId = UUID.randomUUID();
    final Policy input = this.testDataOperations.createPolicy();

    this.policiesApi.createPolicyWithId(policyId, input);

    // Verify it exists
    final Policy beforeDelete = this.policiesApi.getPolicy(policyId);
    assertThat(beforeDelete).isNotNull();

    // Act
    this.policiesApi.deletePolicy(policyId);

    // Assert - should not be found
    assertThatThrownBy(() -> this.policiesApi.getPolicy(policyId))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException restException = (RestClientResponseException) exception;
          assertThat(restException.getStatusCode().value()).isEqualTo(404);
        });
  }

  @Test
  void testListPolicies() {
    // Arrange
    final Policy input1 = this.testDataOperations.createPolicy();

    final Policy input2 = this.testDataOperations.createPolicy();

    this.policiesApi.createPolicy(input1);
    this.policiesApi.createPolicy(input2);

    // Act
    final List<Policy> policies = this.policiesApi.listPolicies();

    // Assert
    assertThat(policies).isNotNull();
    assertThat(policies.size()).isGreaterThanOrEqualTo(2);
    assertThat(policies).extracting(Policy::getName)
        .contains(input1.getName(), input2.getName());
  }

  @Test
  void testPolicyIsolationBetweenOrganizations() {
    // Arrange - Create policy with PM organization
    final UUID policyId = UUID.randomUUID();
    final Policy input = this.testDataOperations.createPolicy();

    this.policiesApi.createPolicyWithId(policyId, input);

    // Act - Try to access with AF organization
    final ApiClient afApiClient = new ApiClient();
    afApiClient.setBasePath("http://localhost:" + this.port);
    afApiClient.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.AF));
    afApiClient.setApiKey(JwtTestUtils.OrganisationType.AF.orgId);
    final PoliciesApi afPoliciesApi = new PoliciesApi(afApiClient);

    // Assert - Should not be found
    assertThatThrownBy(() -> afPoliciesApi.getPolicy(policyId))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException restException = (RestClientResponseException) exception;
          assertThat(restException.getStatusCode().value()).isEqualTo(404);
        });
  }


}

