/*
 * Copyright 2026 Sweden Connect
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package se.swedenconnect.oidf.registry.controller;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.resttestclient.autoconfigure.AutoConfigureRestTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.web.client.RestClient;
import org.springframework.web.client.RestClientResponseException;
import org.testcontainers.containers.MariaDBContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import se.swedenconnect.oidf.registry.ApiClient;
import se.swedenconnect.oidf.registry.api.RegistrationFlowApi;
import se.swedenconnect.oidf.registry.api.model.ConfigValueDto;
import se.swedenconnect.oidf.registry.api.model.FlowSummaryDto;
import se.swedenconnect.oidf.registry.api.model.RegistrationFlowDto;
import se.swedenconnect.oidf.registry.api.model.StepDto;
import se.swedenconnect.oidf.registry.fixture.JwtTestUtils;
import se.swedenconnect.oidf.registry.fixture.TestRestClientFactory;

import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Integration tests for RegistrationFlow CRUD operations.
 *
 * @author Per Fredrik Plars
 */
@Slf4j
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Testcontainers
@AutoConfigureRestTestClient
class RegistrationFlowCRUDIT {

  @Container
  @ServiceConnection
  public static MariaDBContainer<?> database = new MariaDBContainer<>("mariadb:11.2");

  @LocalServerPort
  private int port;

  @Autowired
  private JwtTestUtils jwtTestUtils;

  private RegistrationFlowApi flowApi;
  private RestClient restClient;

  @BeforeEach
  void setUp() {
    final ApiClient apiClient = new ApiClient();
    apiClient.setBasePath("http://localhost:" + this.port);
    apiClient.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.PM));
    apiClient.setApiKey(JwtTestUtils.OrganisationType.PM.orgId);

    this.flowApi = new RegistrationFlowApi(apiClient);
    this.restClient = TestRestClientFactory.createAuthenticated(this.port, null);
  }

  private RegistrationFlowDto validFlow(final String name, final String description) {
    return new RegistrationFlowDto()
        .name(name)
        .description(description)
        .technology(RegistrationFlowDto.TechnologyEnum.OIDC)
        .steps(List.of(new StepDto()
            .stepId(UUID.randomUUID())
            .name("MinimalStep")
            .description("Test step")));
  }

  @Test
  void createFlowWithAutoGeneratedId() {
    final RegistrationFlowDto input = new RegistrationFlowDto()
        .name("Create-Auto Flow")
        .description("Auto ID flow")
        .technology(RegistrationFlowDto.TechnologyEnum.OIDC)
        .steps(List.of(new StepDto()
            .stepId(UUID.randomUUID())
            .name("MetadataValidation")
            .description("Validates Metadata")
            .addConfigItem(new ConfigValueDto()
                .key("entityid")
                .value("https://www.digg.se/entityid"))));

    final RegistrationFlowDto created = this.flowApi.createFlow(input);

    assertThat(created).isNotNull();
    assertThat(created.getFlowId()).isNotNull();
    assertThat(created.getName()).isEqualTo("Create-Auto Flow");
    assertThat(created.getDescription()).isEqualTo("Auto ID flow");
    assertThat(created.getSteps()).hasSize(1);
    assertThat(created.getSteps().getFirst().getName()).isEqualTo("MetadataValidation");
  }

  @Test
  void listFlowsReturnsCreatedFlows() {
    this.flowApi.createFlow(validFlow("List-Flow-A", "First"));
    this.flowApi.createFlow(validFlow("List-Flow-B", "Second"));

    final List<FlowSummaryDto> flows = this.flowApi.listFlows1();

    assertThat(flows).isNotNull().isNotEmpty();
    final FlowSummaryDto first = flows.stream()
        .filter(f -> "List-Flow-A".equals(f.getName()))
        .findFirst().orElseThrow();

    assertThat(first.getName()).isEqualTo("List-Flow-A");
    assertThat(first.getDescription()).isEqualTo("First");
  }

  @Test
  void getFlowById() {
    final RegistrationFlowDto created = this.flowApi.createFlow(validFlow("Get-Flow", "Fetch by ID"));
    final UUID flowId = created.getFlowId();

    final Map<String, Object> retrieved = this.restClient.get()
        .uri("/registration-flow/v1/flow/{id}", flowId)
        .retrieve()
        .body(new ParameterizedTypeReference<>() {});

    assertThat(retrieved).isNotNull();
    assertThat(retrieved.get("name")).isEqualTo("Get-Flow");
    assertThat(retrieved.get("description")).isEqualTo("Fetch by ID");
  }

  @Test
  void getFlowByIdNotFound() {
    assertThatThrownBy(() -> this.restClient.get()
        .uri("/registration-flow/v1/flow/{id}", UUID.randomUUID())
        .retrieve()
        .body(Map.class))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(ex -> assertThat(((RestClientResponseException) ex).getStatusCode().value()).isEqualTo(404));
  }

  @Test
  void updateFlow() {
    final UUID flowId = this.flowApi.createFlow(validFlow("Update-Original", "Before update")).getFlowId();

    final RegistrationFlowDto updated = this.flowApi.updateFlow(flowId,
        validFlow("Update-Changed", "After update"));

    assertThat(updated).isNotNull();
    assertThat(updated.getFlowId()).isEqualTo(flowId);
    assertThat(updated.getName()).isEqualTo("Update-Changed");
    assertThat(updated.getDescription()).isEqualTo("After update");
  }

  @Test
  void updateFlowPersists() {
    final UUID flowId = this.flowApi.createFlow(validFlow("Persist-Original", "Before")).getFlowId();

    this.flowApi.updateFlow(flowId, validFlow("Persist-Updated", "After"));

    final Map<String, Object> retrieved = this.restClient.get()
        .uri("/registration-flow/v1/flow/{id}", flowId)
        .retrieve()
        .body(new ParameterizedTypeReference<>() {});

    assertThat(retrieved).isNotNull();
    assertThat(retrieved.get("name")).isEqualTo("Persist-Updated");
    assertThat(retrieved.get("description")).isEqualTo("After");
  }

  @Test
  void deleteFlow() {
    final UUID flowId = this.flowApi.createFlow(validFlow("Delete-Flow", "Will be deleted")).getFlowId();

    this.flowApi.deleteFlowWithResponseSpec(flowId).toBodilessEntity();

    assertThatThrownBy(() -> this.restClient.get()
        .uri("/registration-flow/v1/flow/{id}", flowId)
        .retrieve()
        .body(Map.class))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(ex -> assertThat(((RestClientResponseException) ex).getStatusCode().value()).isEqualTo(404));
  }

  @Test
  void listFlowsSummaryContainsIdNameDescription() {
    this.flowApi.createFlow(validFlow("Summary-Flow", "Summary desc"));

    final List<Map<String, Object>> summaries = this.restClient.get()
        .uri("/registration-flow/v1/flows")
        .retrieve()
        .body(new ParameterizedTypeReference<>() {});

    final Map<String, Object> match = summaries.stream()
        .filter(s -> "Summary-Flow".equals(s.get("name")))
        .findFirst()
        .orElseThrow();

    assertThat(match.get("flowId")).isNotNull();
    assertThat(match.get("name")).isEqualTo("Summary-Flow");
    assertThat(match.get("description")).isEqualTo("Summary desc");
  }
}