/*
 * Copyright 2026 Sweden Connect
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package se.swedenconnect.oidf.registry.controller;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.resttestclient.autoconfigure.AutoConfigureRestTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.web.client.RestClientResponseException;
import org.testcontainers.containers.MariaDBContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import se.swedenconnect.oidf.registry.ApiClient;
import se.swedenconnect.oidf.registry.api.EntitiesApi;
import se.swedenconnect.oidf.registry.api.ModulesApi;
import se.swedenconnect.oidf.registry.api.TrustmarksApi;
import se.swedenconnect.oidf.registry.api.model.FederationEntity;
import se.swedenconnect.oidf.registry.api.model.Trustmark;
import se.swedenconnect.oidf.registry.api.model.TrustmarkIssuer;
import se.swedenconnect.oidf.registry.api.model.TrustmarkWithSubjects;
import se.swedenconnect.oidf.registry.fixture.JwtTestUtils;

import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Integration tests for TrustmarkIssuer CRUD operations using the generated OpenAPI client.
 *
 * @author Per Fredrik Plars
 */
@Slf4j
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Testcontainers
@AutoConfigureRestTestClient
class TrustmarkIssuerCRUDIT {

  @Container
  @ServiceConnection
  public static MariaDBContainer<?> database = new MariaDBContainer<>("mariadb:11.2");

  @LocalServerPort
  private int port;

  @Autowired
  private JwtTestUtils jwtTestUtils;

  private ModulesApi modulesApi;
  private EntitiesApi entitiesApi;
  private TrustmarksApi trustmarksApi;

  @BeforeEach
  void setUp() {
    final ApiClient apiClient = new ApiClient();
    apiClient.setBasePath("http://localhost:" + this.port);
    apiClient.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.PM));
    apiClient.setApiKey(JwtTestUtils.OrganisationType.PM.orgId);

    this.modulesApi = new ModulesApi(apiClient);
    this.trustmarksApi = new TrustmarksApi(apiClient);
    this.entitiesApi = new EntitiesApi(apiClient);
  }

  private UUID createFederationEntity(final String entityIdentifier) {
    final UUID entityId = UUID.randomUUID();
    this.entitiesApi.createFederationEntityWithId(entityId, new FederationEntity()
        .entityIdentifier(entityIdentifier));
    return entityId;
  }

  @Test
  void createTrustmarkIssuerWithAutoGeneratedId() {
    final UUID entityId = this.createFederationEntity("https://www.pm.se/oidf/tmi-create-auto");

    final TrustmarkIssuer input = new TrustmarkIssuer()
        .entityId(entityId)
        .active(true)
        .trustMarkTokenValidityDuration("PT1H");

    final TrustmarkIssuer created = this.modulesApi.createTrustmarkIssuer(input);

    assertThat(created).isNotNull();
    assertThat(created.getTrustmarkIssuerId()).isNotNull();
    assertThat(created.getEntityId()).isEqualTo(entityId);
    assertThat(created.getActive()).isTrue();
    assertThat(created.getTrustMarkTokenValidityDuration()).isEqualTo("PT1H");
  }

  @Test
  void createTrustmarkIssuerWithSpecifiedId() {
    final UUID entityId = this.createFederationEntity("https://www.pm.se/oidf/tmi-create-specified");
    final UUID issuerId = UUID.randomUUID();

    final TrustmarkIssuer input = new TrustmarkIssuer()
        .entityId(entityId)
        .active(false)
        .trustMarkTokenValidityDuration("PT30M");

    final TrustmarkIssuer created = this.modulesApi.createTrustmarkIssuerWithId(issuerId, input);

    assertThat(created).isNotNull();
    assertThat(created.getTrustmarkIssuerId()).isEqualTo(issuerId);
    assertThat(created.getEntityId()).isEqualTo(entityId);
    assertThat(created.getActive()).isFalse();
    assertThat(created.getTrustMarkTokenValidityDuration()).isEqualTo("PT30M");
  }

  @Test
  void getTrustmarkIssuer() {
    final UUID entityId = this.createFederationEntity("https://www.pm.se/oidf/tmi-get");
    final UUID issuerId = UUID.randomUUID();

    this.modulesApi.createTrustmarkIssuerWithId(issuerId, new TrustmarkIssuer()
        .entityId(entityId)
        .active(true)
        .trustMarkTokenValidityDuration("PT2H"));

    final TrustmarkIssuer retrieved = this.modulesApi.getTrustmarkIssuer(issuerId);

    assertThat(retrieved).isNotNull();
    assertThat(retrieved.getTrustmarkIssuerId()).isEqualTo(issuerId);
    assertThat(retrieved.getEntityId()).isEqualTo(entityId);
    assertThat(retrieved.getActive()).isTrue();
    assertThat(retrieved.getTrustMarkTokenValidityDuration()).isEqualTo("PT2H");
  }

  @Test
  void getTrustmarksOnTrustmarkIssuer() {
    final UUID entityId = this.createFederationEntity("https://www.pm.se/oidf/tmi-listtms");
    final UUID issuerId = UUID.randomUUID();
    final UUID trustmarkId = UUID.randomUUID();

    this.modulesApi.createTrustmarkIssuerWithId(issuerId, new TrustmarkIssuer()
        .entityId(entityId)
        .active(true)
        .trustMarkTokenValidityDuration("PT2H"));

    this.trustmarksApi.createTrustmarkWithId(trustmarkId, new Trustmark()
        .trustmarkType("https://loa3.sc.se")
        .trustmarkissuerId(issuerId));

    final List<TrustmarkWithSubjects> trustmarkWithSubjects = this.modulesApi.getTrustmarks(issuerId);

    assertThat(trustmarkWithSubjects).isNotNull();
    assertThat(trustmarkWithSubjects.size()).isEqualTo(1);
    assertThat(trustmarkWithSubjects.get(0).getTrustmarkId()).isEqualTo(trustmarkId);
    assertThat(trustmarkWithSubjects.get(0).getTrustmarkissuerId()).isEqualTo(issuerId);
  }

  @Test
  void updateTrustmarkIssuer() {
    final UUID entityId = this.createFederationEntity("https://www.pm.se/oidf/tmi-updates");
    final UUID issuerId = UUID.randomUUID();

    this.modulesApi.createTrustmarkIssuerWithId(issuerId, new TrustmarkIssuer()
        .entityId(entityId)
        .active(true)
        .trustMarkTokenValidityDuration("PT1H"));

    final TrustmarkIssuer updated = this.modulesApi.updateTrustmarkIssuer(issuerId, new TrustmarkIssuer()
        .entityId(entityId)
        .active(false)
        .trustMarkTokenValidityDuration("PT4H"));

    assertThat(updated).isNotNull();
    assertThat(updated.getTrustmarkIssuerId()).isEqualTo(issuerId);
    assertThat(updated.getActive()).isFalse();
    assertThat(updated.getTrustMarkTokenValidityDuration()).isEqualTo("PT4H");
  }

  @Test
  void deleteTrustmarkIssuer() {
    final UUID entityId = this.createFederationEntity("https://www.pm.se/oidf/tmi-delete");
    final UUID issuerId = UUID.randomUUID();

    this.modulesApi.createTrustmarkIssuerWithId(issuerId, new TrustmarkIssuer()
        .entityId(entityId)
        .active(true)
        .trustMarkTokenValidityDuration("PT1H"));

    assertThat(this.modulesApi.getTrustmarkIssuer(issuerId)).isNotNull();

    this.modulesApi.deleteTrustmarkIssuer(issuerId);

    assertThatThrownBy(() -> this.modulesApi.getTrustmarkIssuer(issuerId))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(ex -> assertThat(((RestClientResponseException) ex).getStatusCode().value()).isEqualTo(404));
  }

  @Test
  void getTrustmarkIssuerNotFound() {
    assertThatThrownBy(() -> this.modulesApi.getTrustmarkIssuer(UUID.randomUUID()))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(ex -> assertThat(((RestClientResponseException) ex).getStatusCode().value()).isEqualTo(404));
  }

  @Test
  void trustmarkIssuerIsolationBetweenOrganizations() {
    // Create issuer for PM org
    final UUID pmEntityId = this.createFederationEntity("https://www.pm.se/oidf/tmi-isolation");
    final UUID pmIssuerId = UUID.randomUUID();
    this.modulesApi.createTrustmarkIssuerWithId(pmIssuerId, new TrustmarkIssuer()
        .entityId(pmEntityId)
        .active(true)
        .trustMarkTokenValidityDuration("PT1H"));

    // AF org should not be able to access PM's issuer
    final ApiClient afClient = new ApiClient();
    afClient.setBasePath("http://localhost:" + this.port);
    afClient.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.AF));
    afClient.setApiKey(JwtTestUtils.OrganisationType.AF.orgId);
    final ModulesApi afModulesApi = new ModulesApi(afClient);

    assertThatThrownBy(() -> afModulesApi.getTrustmarkIssuer(pmIssuerId))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(ex -> assertThat(((RestClientResponseException) ex).getStatusCode().value()).isEqualTo(404));
  }
}