/*
 * Copyright 2025 Sweden Connect
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package se.swedenconnect.oidf.registry.controller;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.testcontainers.containers.MariaDBContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import se.swedenconnect.oidf.registry.ApiClient;
import se.swedenconnect.oidf.registry.ApiException;
import se.swedenconnect.oidf.registry.api.EntitiesApi;
import se.swedenconnect.oidf.registry.api.ModulesApi;
import se.swedenconnect.oidf.registry.api.TrustmarkSubjectsApi;
import se.swedenconnect.oidf.registry.api.model.HostedEntityInput;
import se.swedenconnect.oidf.registry.api.model.TrustAnchorInput;
import se.swedenconnect.oidf.registry.api.model.TrustmarkInput;
import se.swedenconnect.oidf.registry.api.model.TrustmarkSubject;
import se.swedenconnect.oidf.registry.api.model.TrustmarkSubjectInput;
import se.swedenconnect.oidf.registry.auth.HttpBearerAuth;
import se.swedenconnect.oidf.registry.fixture.JwtTestUtils;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Integration tests for TrustmarkSubject CRUD operations using the generated OpenAPI client.
 *
 * @author Per Fredrik Plars
 */
@Slf4j
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Testcontainers
class TrustmarkSubjectCRUDIT {

  @Container
  @ServiceConnection
  public static MariaDBContainer<?> database = new MariaDBContainer<>("mariadb:11.2");

  @LocalServerPort
  private int port;

  @Autowired
  private JwtTestUtils jwtTestUtils;

  private TrustmarkSubjectsApi trustmarkSubjectsApi;
  private ModulesApi modulesApi;
  private EntitiesApi entitiesApi;
  private ApiClient apiClient;

  @BeforeEach
  void setUp() {
    this.apiClient = new ApiClient();
    this.apiClient.setBasePath("http://localhost:" + this.port);

    // Configure authentication
    final HttpBearerAuth bearerAuth = (HttpBearerAuth) this.apiClient.getAuthentication("bearerAuth");
    bearerAuth.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.PM));

    // Configure selected org number
    this.apiClient.addDefaultHeader("selected-org-number", JwtTestUtils.OrganisationType.PM.orgId);

    this.trustmarkSubjectsApi = new TrustmarkSubjectsApi(this.apiClient);
    this.modulesApi = new ModulesApi(this.apiClient);
    this.entitiesApi = new EntitiesApi(this.apiClient);
  }

  private UUID createTrustmark() throws ApiException {
    // Create a hosted entity
    final UUID entityId = UUID.randomUUID();
    final HostedEntityInput entityInput = new HostedEntityInput()
        .subject("http://www.pm.se/oidf/tmi-entity")
        .issuer("http://www.pm.se/oidf/tmi-entity");
    this.entitiesApi.createHostedEntityWithId(entityId, entityInput);

    // Create a trust anchor
    final UUID taModuleId = UUID.randomUUID();
    final TrustAnchorInput taInput = new TrustAnchorInput()
        .entityId("http://www.pm.se/oidf/tmi-entity")
        .active(true);
    this.modulesApi.createTrustAnchorWithId(taModuleId, taInput);

    // Create a trustmark
    final UUID trustmarkId = UUID.randomUUID();
    final TrustmarkInput trustmarkInput = new TrustmarkInput()
        .trustmarkissuerId("http://www.pm.se/oidf/tmi-entity")
        .trustMarkEntityId("http://www.pm.se/oidf/trustmark");
    this.modulesApi.createTrustmarkWithId(trustmarkId, trustmarkInput);

    return trustmarkId;
  }

  @Test
  void testCreateTrustmarkSubjectWithAutoGeneratedId() throws ApiException {
    // Arrange
    final UUID trustmarkId = this.createTrustmark();
    final TrustmarkSubjectInput input = new TrustmarkSubjectInput()
        .trustmarkId(trustmarkId.toString())
        .subject("http://www.pm.se/oidf/subject")
        .revoked(false)
        .granted("2025-01-01T00:00:00")
        .expires("2026-01-01T00:00:00");

    // Act
    final TrustmarkSubject created = this.trustmarkSubjectsApi.createTrustmarkSubject(input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getTrustmarksubjectId()).isNotNull();
    assertThat(created.getTrustmarkId()).isEqualTo(trustmarkId.toString());
    assertThat(created.getSubject()).isEqualTo("http://www.pm.se/oidf/subject");
    assertThat(created.getRevoked()).isFalse();
    assertThat(created.getGranted()).isNotNull();
    assertThat(created.getExpires()).isNotNull();
  }

  @Test
  void testCreateTrustmarkSubjectWithSpecifiedId() throws ApiException {
    // Arrange
    final UUID trustmarkId = this.createTrustmark();
    final UUID subjectId = UUID.randomUUID();
    final TrustmarkSubjectInput input = new TrustmarkSubjectInput()
        .trustmarkId(trustmarkId.toString())
        .subject("http://www.pm.se/oidf/subject2")
        .revoked(true);

    // Act
    final TrustmarkSubject created = this.trustmarkSubjectsApi.createTrustmarkSubjectWithId(subjectId, input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getTrustmarksubjectId()).isEqualTo(subjectId);
    assertThat(created.getSubject()).isEqualTo("http://www.pm.se/oidf/subject2");
    assertThat(created.getRevoked()).isTrue();
  }

  @Test
  void testGetTrustmarkSubject() throws ApiException {
    // Arrange
    final UUID trustmarkId = this.createTrustmark();
    final UUID subjectId = UUID.randomUUID();
    final TrustmarkSubjectInput input = new TrustmarkSubjectInput()
        .trustmarkId(trustmarkId.toString())
        .subject("http://www.pm.se/oidf/subject3")
        .revoked(false);
    this.trustmarkSubjectsApi.createTrustmarkSubjectWithId(subjectId, input);

    // Act
    final TrustmarkSubject retrieved = this.trustmarkSubjectsApi.getTrustmarkSubject(subjectId);

    // Assert
    assertThat(retrieved).isNotNull();
    assertThat(retrieved.getTrustmarksubjectId()).isEqualTo(subjectId);
    assertThat(retrieved.getTrustmarkId()).isEqualTo(trustmarkId.toString());
    assertThat(retrieved.getSubject()).isEqualTo("http://www.pm.se/oidf/subject3");
  }

  @Test
  void testGetTrustmarkSubjectNotFound() {
    // Arrange
    final UUID nonExistentId = UUID.randomUUID();

    // Act & Assert
    assertThatThrownBy(() -> this.trustmarkSubjectsApi.getTrustmarkSubject(nonExistentId))
        .isInstanceOf(ApiException.class)
        .satisfies(exception -> {
          final ApiException apiException = (ApiException) exception;
          assertThat(apiException.getCode()).isEqualTo(404);
        });
  }

  @Test
  void testUpdateTrustmarkSubject() throws ApiException {
    // Arrange
    final UUID trustmarkId = this.createTrustmark();
    final UUID subjectId = UUID.randomUUID();
    final TrustmarkSubjectInput createInput = new TrustmarkSubjectInput()
        .trustmarkId(trustmarkId.toString())
        .subject("http://www.pm.se/oidf/subject4")
        .revoked(false);
    this.trustmarkSubjectsApi.createTrustmarkSubjectWithId(subjectId, createInput);

    final TrustmarkSubjectInput updateInput = new TrustmarkSubjectInput()
        .trustmarkId(trustmarkId.toString())
        .subject("http://www.pm.se/oidf/subject4-updated")
        .revoked(true)
        .granted("2025-02-01T00:00:00")
        .expires("2026-02-01T00:00:00");

    // Act
    final TrustmarkSubject updated = this.trustmarkSubjectsApi.updateTrustmarkSubject(subjectId, updateInput);

    // Assert
    assertThat(updated).isNotNull();
    assertThat(updated.getSubject()).isEqualTo("http://www.pm.se/oidf/subject4-updated");
    assertThat(updated.getRevoked()).isTrue();
    assertThat(updated.getGranted()).isNotNull();
    assertThat(updated.getExpires()).isNotNull();

    // Verify by getting again
    final TrustmarkSubject retrieved = this.trustmarkSubjectsApi.getTrustmarkSubject(subjectId);
    assertThat(retrieved.getSubject()).isEqualTo("http://www.pm.se/oidf/subject4-updated");
    assertThat(retrieved.getRevoked()).isTrue();
  }

  @Test
  void testDeleteTrustmarkSubject() throws ApiException {
    // Arrange
    final UUID trustmarkId = this.createTrustmark();
    final UUID subjectId = UUID.randomUUID();
    final TrustmarkSubjectInput input = new TrustmarkSubjectInput()
        .trustmarkId(trustmarkId.toString())
        .subject("http://www.pm.se/oidf/subject5")
        .revoked(false);
    this.trustmarkSubjectsApi.createTrustmarkSubjectWithId(subjectId, input);

    // Verify it exists
    final TrustmarkSubject beforeDelete = this.trustmarkSubjectsApi.getTrustmarkSubject(subjectId);
    assertThat(beforeDelete).isNotNull();

    // Act
    this.trustmarkSubjectsApi.deleteTrustmarkSubject(subjectId);

    // Assert - should not be found
    assertThatThrownBy(() -> this.trustmarkSubjectsApi.getTrustmarkSubject(subjectId))
        .isInstanceOf(ApiException.class)
        .satisfies(exception -> {
          final ApiException apiException = (ApiException) exception;
          assertThat(apiException.getCode()).isEqualTo(404);
        });
  }

  @Test
  void testTrustmarkSubjectWithDateTimeFields() throws ApiException {
    // Arrange
    final UUID trustmarkId = this.createTrustmark();
    final TrustmarkSubjectInput input = new TrustmarkSubjectInput()
        .trustmarkId(trustmarkId.toString())
        .subject("http://www.pm.se/oidf/subject-datetime")
        .revoked(false)
        .granted("2025-01-15T10:30:00")
        .expires("2025-12-31T23:59:59");

    // Act
    final TrustmarkSubject created = this.trustmarkSubjectsApi.createTrustmarkSubject(input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getGranted()).isNotNull();
    assertThat(created.getExpires()).isNotNull();
    // Verify the dates are parsed correctly
    assertThat(created.getGranted().getYear()).isEqualTo(2025);
    assertThat(created.getGranted().getMonthValue()).isEqualTo(1);
    assertThat(created.getGranted().getDayOfMonth()).isEqualTo(15);
  }

  @Test
  void testTrustmarkSubjectIsolationBetweenOrganizations() throws ApiException {
    // Arrange - Create trustmark subject with PM organization
    final UUID trustmarkId = this.createTrustmark();
    final UUID subjectId = UUID.randomUUID();
    final TrustmarkSubjectInput input = new TrustmarkSubjectInput()
        .trustmarkId(trustmarkId.toString())
        .subject("http://www.pm.se/oidf/pm-subject")
        .revoked(false);
    this.trustmarkSubjectsApi.createTrustmarkSubjectWithId(subjectId, input);

    // Act - Try to access with AF organization
    final ApiClient afApiClient = new ApiClient();
    afApiClient.setBasePath("http://localhost:" + this.port);
    final HttpBearerAuth afBearerAuth = (HttpBearerAuth) afApiClient.getAuthentication("bearerAuth");
    afBearerAuth.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.AF));
    afApiClient.addDefaultHeader("selected-org-number", JwtTestUtils.OrganisationType.AF.orgId);
    final TrustmarkSubjectsApi afTrustmarkSubjectsApi = new TrustmarkSubjectsApi(afApiClient);

    // Assert - Should not be found
    assertThatThrownBy(() -> afTrustmarkSubjectsApi.getTrustmarkSubject(subjectId))
        .isInstanceOf(ApiException.class)
        .satisfies(exception -> {
          final ApiException apiException = (ApiException) exception;
          assertThat(apiException.getCode()).isEqualTo(404);
        });
  }
}

