/*
 * Copyright 2026 Sweden Connect
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package se.swedenconnect.oidf.registry.controller;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.web.client.RestClientResponseException;
import org.testcontainers.containers.MariaDBContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import se.swedenconnect.oidf.registry.ApiClient;
import se.swedenconnect.oidf.registry.api.EntitiesApi;
import se.swedenconnect.oidf.registry.api.ModulesApi;
import se.swedenconnect.oidf.registry.api.TrustmarksApi;
import se.swedenconnect.oidf.registry.api.model.FederationEntity;
import se.swedenconnect.oidf.registry.api.model.Trustmark;
import se.swedenconnect.oidf.registry.api.model.TrustmarkIssuer;
import se.swedenconnect.oidf.registry.api.model.TrustmarkSubject;
import se.swedenconnect.oidf.registry.fixture.JwtTestUtils;

import java.time.OffsetDateTime;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Integration tests for TrustmarkSubject CRUD operations using the generated OpenAPI client.
 *
 * @author Per Fredrik Plars
 */
@Slf4j
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Testcontainers
class TrustmarkSubjectCRUDIT {

  @Container
  @ServiceConnection
  public static MariaDBContainer<?> database = new MariaDBContainer<>("mariadb:11.2");

  @LocalServerPort
  private int port;

  @Autowired
  private JwtTestUtils jwtTestUtils;

  private TrustmarksApi trustmarksApi;
  private ModulesApi modulesApi;
  private EntitiesApi entitiesApi;
  private ApiClient apiClient;

  @BeforeEach
  void setUp() {
    this.apiClient = new ApiClient();
    this.apiClient.setBasePath("http://localhost:" + this.port);

    // Configure authentication
    this.apiClient.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.PM));
    this.apiClient.setApiKey(JwtTestUtils.OrganisationType.PM.orgId);

    this.trustmarksApi = new TrustmarksApi(this.apiClient);
    this.modulesApi = new ModulesApi(this.apiClient);
    this.entitiesApi = new EntitiesApi(this.apiClient);
  }

  /**
   * Helper method to create a TrustmarkIssuer. This is needed because trustmarks require a TrustmarkIssuer to exist.
   *
   * @param entityId the entity ID to associate the trustmark issuer with
   * @return the created trustmark issuer ID
   */
  private UUID createTrustmarkIssuer(final UUID entityId) {
    final UUID trustmarkIssuerId = UUID.randomUUID();
    final TrustmarkIssuer issuerInput = new TrustmarkIssuer()
        .entityId(entityId)
        .active(true)
        .trustMarkTokenValidityDuration("PT1H");

    final TrustmarkIssuer createdIssuer = this.modulesApi.createTrustmarkIssuerWithId(trustmarkIssuerId, issuerInput);
    return createdIssuer.getTrustmarkIssuerId();
  }

  private UUID createTrustmark() {
    // Create a hosted entity
    final UUID entityId = UUID.randomUUID();
    final FederationEntity entityInput = new FederationEntity()
        .entityIdentifier("https://www.pm.se/oidf/tmi-entity/" + UUID.randomUUID());
    this.entitiesApi.createFederationEntityWithId(entityId, entityInput);

    // Create a TrustmarkIssuer
    final UUID trustmarkIssuerId = this.createTrustmarkIssuer(entityId);

    // Create a trustmark
    final UUID trustmarkId = UUID.randomUUID();
    final Trustmark trustmarkInput = new Trustmark()
        .trustmarkissuerId(trustmarkIssuerId)
        .trustmarkType("https://www.pm.se/oidf/loa3");
    this.trustmarksApi.createTrustmarkWithId(trustmarkId, trustmarkInput);
    return trustmarkId;
  }

  @Test
  void testCreateTrustmarkSubjectWithAutoGeneratedId() {
    // Arrange
    final UUID trustmarkId = this.createTrustmark();
    final TrustmarkSubject input = new TrustmarkSubject()
        .trustmarkId(trustmarkId)
        .subject("https://www.pm.se/oidf/subject")
        .revoked(false)
        .granted(OffsetDateTime.parse("2025-01-01T00:00:00+01:00"))
        .expires(OffsetDateTime.parse("2026-01-01T00:00:00+01:00"));

    // Act
    final TrustmarkSubject created = this.trustmarksApi.createTrustmarkSubject(input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getTrustmarksubjectId()).isNotNull();
    assertThat(created.getTrustmarkId()).isEqualTo(trustmarkId);
    assertThat(created.getSubject()).isEqualTo("https://www.pm.se/oidf/subject");
    assertThat(created.getRevoked()).isFalse();
    assertThat(created.getGranted()).isNotNull();
    assertThat(created.getExpires()).isNotNull();
  }

  @Test
  void testCreateTrustmarkSubjectWithSpecifiedId() {
    // Arrange
    final UUID trustmarkId = this.createTrustmark();
    final UUID subjectId = UUID.randomUUID();
    final TrustmarkSubject input = new TrustmarkSubject()
        .trustmarkId(trustmarkId)
        .subject("https://www.pm.se/oidf/subject2")
        .revoked(true);

    // Act
    final TrustmarkSubject created = this.trustmarksApi.createTrustmarkSubjectWithId(subjectId, input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getTrustmarksubjectId()).isEqualTo(subjectId);
    assertThat(created.getSubject()).isEqualTo("https://www.pm.se/oidf/subject2");
    assertThat(created.getRevoked()).isTrue();
  }

  @Test
  void testGetTrustmarkSubject() {
    // Arrange
    final UUID trustmarkId = this.createTrustmark();
    final UUID subjectId = UUID.randomUUID();
    final TrustmarkSubject input = new TrustmarkSubject()
        .trustmarkId(trustmarkId)
        .subject("https://www.pm.se/oidf/subject3")
        .revoked(false);
    this.trustmarksApi.createTrustmarkSubjectWithId(subjectId, input);

    // Act
    final TrustmarkSubject retrieved = this.trustmarksApi.getTrustmarkSubject(subjectId);

    // Assert
    assertThat(retrieved).isNotNull();
    assertThat(retrieved.getTrustmarksubjectId()).isEqualTo(subjectId);
    assertThat(retrieved.getTrustmarkId()).isEqualTo(trustmarkId);
    assertThat(retrieved.getSubject()).isEqualTo("https://www.pm.se/oidf/subject3");
  }

  @Test
  void testGetTrustmarkSubjectNotFound() {
    // Arrange
    final UUID nonExistentId = UUID.randomUUID();

    // Act & Assert
    assertThatThrownBy(() -> this.trustmarksApi.getTrustmarkSubject(nonExistentId))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException apiException = (RestClientResponseException) exception;
          assertThat(apiException.getStatusCode().value()).isEqualTo(404);
        });
  }

  @Test
  void testUpdateTrustmarkSubject() {
    // Arrange
    final UUID trustmarkId = this.createTrustmark();
    final UUID subjectId = UUID.randomUUID();
    final TrustmarkSubject createInput = new TrustmarkSubject()
        .trustmarkId(trustmarkId)
        .subject("https://www.pm.se/oidf/subject4")
        .revoked(false);
    this.trustmarksApi.createTrustmarkSubjectWithId(subjectId, createInput);

    final TrustmarkSubject updateInput = new TrustmarkSubject()
        .trustmarkId(trustmarkId)
        .subject("https://www.pm.se/oidf/subject4-updated")
        .revoked(true)
        .granted(OffsetDateTime.parse("2025-01-01T00:00:00+01:00"))
        .expires(OffsetDateTime.parse("2026-01-01T00:00:00+01:00"));

    // Act
    final TrustmarkSubject updated = this.trustmarksApi.updateTrustmarkSubject(subjectId, updateInput);

    // Assert
    assertThat(updated).isNotNull();
    assertThat(updated.getSubject()).isEqualTo("https://www.pm.se/oidf/subject4-updated");
    assertThat(updated.getRevoked()).isTrue();
    assertThat(updated.getGranted()).isNotNull();
    assertThat(updated.getExpires()).isNotNull();

    // Verify by getting again
    final TrustmarkSubject retrieved = this.trustmarksApi.getTrustmarkSubject(subjectId);
    assertThat(retrieved.getSubject()).isEqualTo("https://www.pm.se/oidf/subject4-updated");
    assertThat(retrieved.getRevoked()).isTrue();
  }

  @Test
  void testDeleteTrustmarkSubject() {
    // Arrange
    final UUID trustmarkId = this.createTrustmark();
    final UUID subjectId = UUID.randomUUID();
    final TrustmarkSubject input = new TrustmarkSubject()
        .trustmarkId(trustmarkId)
        .subject("https://www.pm.se/oidf/subject5")
        .revoked(false);
    this.trustmarksApi.createTrustmarkSubjectWithId(subjectId, input);

    // Verify it exists
    final TrustmarkSubject beforeDelete = this.trustmarksApi.getTrustmarkSubject(subjectId);
    assertThat(beforeDelete).isNotNull();

    // Act
    this.trustmarksApi.deleteTrustmarkSubject(subjectId);

    // Assert - should not be found
    assertThatThrownBy(() -> this.trustmarksApi.getTrustmarkSubject(subjectId))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException apiException = (RestClientResponseException) exception;
          assertThat(apiException.getStatusCode().value()).isEqualTo(404);
        });
  }

  @Test
  void testTrustmarkSubjectWithDateTimeFields() {
    // Arrange
    final UUID trustmarkId = this.createTrustmark();
    final TrustmarkSubject input = new TrustmarkSubject()
        .trustmarkId(trustmarkId)
        .subject("https://www.pm.se/oidf/subject-datetime")
        .revoked(false)
        .granted(OffsetDateTime.parse("2025-01-15T00:00:00+00:00"))
        .expires(OffsetDateTime.parse("2026-01-01T00:00:00+00:00"));

    // Act
    final TrustmarkSubject created = this.trustmarksApi.createTrustmarkSubject(input);

    // Assert
    assertThat(created).isNotNull();
    assertThat(created.getGranted()).isNotNull();
    assertThat(created.getExpires()).isNotNull();
    // Verify the dates are parsed correctly
    assertThat(created.getGranted().getYear()).isEqualTo(2025);
    assertThat(created.getGranted().getMonthValue()).isEqualTo(1);
    assertThat(created.getGranted().getDayOfMonth()).isEqualTo(15);
  }

  @Test
  void testTrustmarkSubjectIsolationBetweenOrganizations() {
    // Arrange - Create trustmark subject with PM organization
    final UUID trustmarkId = this.createTrustmark();
    final UUID subjectId = UUID.randomUUID();
    final TrustmarkSubject input = new TrustmarkSubject()
        .trustmarkId(trustmarkId)
        .subject("https://www.pm.se/oidf/pm-subject")
        .revoked(false);
    this.trustmarksApi.createTrustmarkSubjectWithId(subjectId, input);

    // Act - Try to access with AF organization
    final ApiClient afApiClient = new ApiClient();
    afApiClient.setBasePath("http://localhost:" + this.port);
    afApiClient.setBearerToken(this.jwtTestUtils.createJwt(JwtTestUtils.OrganisationType.AF));
    afApiClient.setApiKey(JwtTestUtils.OrganisationType.AF.orgId);
    final TrustmarksApi trApi = new TrustmarksApi(afApiClient);

    // Assert - Should not be found
    assertThatThrownBy(() -> trApi.getTrustmarkSubject(subjectId))
        .isInstanceOf(RestClientResponseException.class)
        .satisfies(exception -> {
          final RestClientResponseException restException = (RestClientResponseException) exception;
          assertThat(restException.getStatusCode().value()).isEqualTo(404);
        });
  }
}

