/*
 * Copyright 2025 Sweden Connect
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 *  limitations under the License.
 */
create table entities
(
    created_date       timestamp(6) not null,
    id                 bigint generated by default as identity,
    last_modified_date timestamp(6) not null,
    created_by         varchar(255),
    entity             TEXT,
    external_id        varchar(255) not null unique,
    issuer             varchar(255) not null,
    last_modified_by   varchar(255),
    subject            varchar(255) not null,
    primary key (id),
    unique (issuer, subject)
);
create table instance
(
    created_date       timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_modified_date timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by         varchar(255),
    instance_id        varchar(255)                           not null,
    last_modified_by   varchar(255),
    name               varchar(255),
    primary key (instance_id)
);
create table module
(
    active             tinyint                                not null,
    created_date       timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_modified_date timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    external_id        varchar(100)                           not null unique,
    created_by         varchar(255),
    issuer_entity_id   varchar(255)                           not null,
    last_modified_by   varchar(255),
    module_id          varchar(255)                           not null,
    module_type        varchar(255)                           not null,
    primary key (module_id),
    unique (module_id, module_type)
);
create table organisation
(
    organisation_id    integer generated by default as identity,
    created_date       timestamp(6) not null,
    last_modified_date timestamp(6) not null,
    created_by         varchar(255),
    entityid_filter    varchar(255),
    last_modified_by   varchar(255),
    organisation       varchar(255),
    primary key (organisation_id)
);
create table policies
(
    created_date       timestamp(6) not null,
    id                 bigint generated by default as identity,
    last_modified_date timestamp(6) not null,
    created_by         varchar(255),
    external_id        varchar(255) not null unique,
    last_modified_by   varchar(255),
    name               varchar(255),
    policy             TEXT,
    primary key (id)
);
create table settings
(
    created_date       timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_modified_date timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    property_id        bigint generated by default as identity,
    created_by         varchar(255),
    description        varchar(255),
    fk_id              varchar(255)                           not null,
    fk_type            varchar(255)                           not null,
    data_key           varchar(255)                           not null,
    last_modified_by   varchar(255),
    validation         varchar(255),
    data_value         varchar(255),
    data_type          varchar(255),
    primary key (property_id)
);
create table trustmark_subject
(
    created_date          timestamp(6) not null,
    id                    bigint generated by default as identity,
    last_modified_date    timestamp(6) not null,
    created_by            varchar(255),
    external_id           varchar(255) not null unique,
    issuer                varchar(255) not null,
    last_modified_by      varchar(255),
    subject               varchar(255) not null,
    trustmark_id          varchar(255) not null,
    trustmarksubject_json TEXT         not null,
    primary key (id),
    unique (issuer, trustmark_id, subject)
);
