name: Automated publication of docker image
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - main

jobs:
  publish-docker:
    uses: swedenconnect/openid-federation-commons/.github/workflows/reusable-publish.yml@main
    with:
      service-path: service
