name: Automated publication of docker image
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - main

jobs:
  publish-docker:
    uses: swedenconnect/openid-federation-commons/.github/workflows/docker-ghcr-publish.yml@workflow
    secrets: inherit
    with:
      service-path: service
