name: Automated review steps
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: s4u/maven-settings-action@v3.1.0
        with:
          repositories: '[{"id":"github","url":"https://maven.pkg.github.com/swedenconnect/*",
          "snapshots":{"enabled":true}}]'
          servers: '[{"id": "github", "username": "${{github.actor}}", "password": "${{secrets.GITHUB_TOKEN}}"}]'
          githubServer: false
      - uses: actions/setup-java@v4
        name: Compile
        with:
          distribution: 'temurin'
          java-version: '21'
          overwrite-settings: false
      - run: mvn compile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-java@v4
        name: Verify
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: mvn verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}