name: Automated review steps
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        env:
          GITHUB_USER: ${{github.user}}
          GITHUB_PASSWORD: ${{secrets.GITHUB_TOKEN}}
      - run: USER=$GITHUB_USER PASSWORD=$GITHUB_PASSWORD < .github/settings.xml > .github/settings-out.xml
      - run: echo "u:$GITHUB_USER"
      - uses: actions/setup-java@v4
        name: Verify
        with:
          distribution: 'temurin'
          java-version: '21'
          overwrite-setting: false
      - run: mvn verify --settings .github/settings-out.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}